/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  HealthOutputBody
} from '../../models';


export const getHealthCheckResponseMock = (overrideResponse: Partial<Extract<HealthOutputBody, object>> = {}): HealthOutputBody => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), status: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

