/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  HealthOutputBody
} from '../../models';

import {
  getHealthCheckResponseMock
} from './health.faker';

export { getHealthCheckResponseMock } from './health.faker';


export const getHealthCheckMockHandler = (overrideResponse?: HealthOutputBody | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HealthOutputBody> | HealthOutputBody), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/health', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getHealthCheckResponseMock(),
      { status: 200
      })
  }, options)
}
export const getHealthMock = () => [
  getHealthCheckMockHandler()
]
