/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreateEssayBody,
  ErrorModel,
  EssayBody,
  EssayListBody,
  UpdateEssayGroupBody,
  UpdateStatusBody
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type getEssaysByGroupResponse200 = {
  data: EssayListBody
  status: 200
}

export type getEssaysByGroupResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getEssaysByGroupResponseSuccess = (getEssaysByGroupResponse200) & {
  headers: Headers;
};
export type getEssaysByGroupResponseError = (getEssaysByGroupResponseDefault) & {
  headers: Headers;
};

export type getEssaysByGroupResponse = (getEssaysByGroupResponseSuccess | getEssaysByGroupResponseError)

export const getGetEssaysByGroupUrl = (essayGroupId: string,) => {




  return `/api/essay-groups/${essayGroupId}/essays`
}

/**
 * Shows all essays belonging to an essay group
 */
export const getEssaysByGroup = async (essayGroupId: string, options?: RequestInit): Promise<getEssaysByGroupResponse> => {

  const res = await fetch(getGetEssaysByGroupUrl(essayGroupId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getEssaysByGroupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getEssaysByGroupResponse
}




export const getGetEssaysByGroupKey = (essayGroupId: string,) => [`/api/essay-groups/${essayGroupId}/essays`] as const;

export type GetEssaysByGroupQueryResult = NonNullable<Awaited<ReturnType<typeof getEssaysByGroup>>>

export const useGetEssaysByGroup = <TError = Promise<ErrorModel>>(
  essayGroupId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getEssaysByGroup>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && essayGroupId !== null && essayGroupId !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetEssaysByGroupKey(essayGroupId) : null);
  const swrFn = () => getEssaysByGroup(essayGroupId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type createEssayResponse204 = {
  data: void
  status: 204
}

export type createEssayResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type createEssayResponseSuccess = (createEssayResponse204) & {
  headers: Headers;
};
export type createEssayResponseError = (createEssayResponseDefault) & {
  headers: Headers;
};

export type createEssayResponse = (createEssayResponseSuccess | createEssayResponseError)

export const getCreateEssayUrl = () => {




  return `/api/essays`
}

/**
 * Creates an essay with the logged in student
 */
export const createEssay = async (createEssayBody: NonReadonly<CreateEssayBody>, options?: RequestInit): Promise<createEssayResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateEssayUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createEssayBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createEssayResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as createEssayResponse
}




export const getCreateEssayMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<CreateEssayBody> }) => {
    return createEssay(arg, options);
  }
}
export const getCreateEssayMutationKey = () => [`/api/essays`] as const;

export type CreateEssayMutationResult = NonNullable<Awaited<ReturnType<typeof createEssay>>>

export const useCreateEssay = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createEssay>>, TError, Key, NonReadonly<CreateEssayBody>, Awaited<ReturnType<typeof createEssay>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateEssayMutationKey();
  const swrFn = getCreateEssayMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type updateEssayGroupResponse200 = {
  data: EssayBody
  status: 200
}

export type updateEssayGroupResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateEssayGroupResponseSuccess = (updateEssayGroupResponse200) & {
  headers: Headers;
};
export type updateEssayGroupResponseError = (updateEssayGroupResponseDefault) & {
  headers: Headers;
};

export type updateEssayGroupResponse = (updateEssayGroupResponseSuccess | updateEssayGroupResponseError)

export const getUpdateEssayGroupUrl = (essayId: string,) => {




  return `/api/essays/${essayId}/group`
}

/**
 * Adds an essay to a group, moves it to another group, or removes it from its group
 */
export const updateEssayGroup = async (essayId: string,
    updateEssayGroupBody: NonReadonly<UpdateEssayGroupBody>, options?: RequestInit): Promise<updateEssayGroupResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getUpdateEssayGroupUrl(essayId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateEssayGroupBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateEssayGroupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateEssayGroupResponse
}




export const getUpdateEssayGroupMutationFetcher = (essayId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<UpdateEssayGroupBody> }) => {
    return updateEssayGroup(essayId, arg, options);
  }
}
export const getUpdateEssayGroupMutationKey = (essayId: string,) => [`/api/essays/${essayId}/group`] as const;

export type UpdateEssayGroupMutationResult = NonNullable<Awaited<ReturnType<typeof updateEssayGroup>>>

export const useUpdateEssayGroup = <TError = Promise<ErrorModel>>(
  essayId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateEssayGroup>>, TError, Key, NonReadonly<UpdateEssayGroupBody>, Awaited<ReturnType<typeof updateEssayGroup>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateEssayGroupMutationKey(essayId);
  const swrFn = getUpdateEssayGroupMutationFetcher(essayId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type updateEssayStatusResponse200 = {
  data: EssayBody
  status: 200
}

export type updateEssayStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateEssayStatusResponseSuccess = (updateEssayStatusResponse200) & {
  headers: Headers;
};
export type updateEssayStatusResponseError = (updateEssayStatusResponseDefault) & {
  headers: Headers;
};

export type updateEssayStatusResponse = (updateEssayStatusResponseSuccess | updateEssayStatusResponseError)

export const getUpdateEssayStatusUrl = (essayId: string,) => {




  return `/api/essays/${essayId}/status`
}

/**
 * updates the status of a students essay
 */
export const updateEssayStatus = async (essayId: string,
    updateStatusBody: NonReadonly<UpdateStatusBody>, options?: RequestInit): Promise<updateEssayStatusResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getUpdateEssayStatusUrl(essayId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateStatusBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateEssayStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateEssayStatusResponse
}




export const getUpdateEssayStatusMutationFetcher = (essayId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<UpdateStatusBody> }) => {
    return updateEssayStatus(essayId, arg, options);
  }
}
export const getUpdateEssayStatusMutationKey = (essayId: string,) => [`/api/essays/${essayId}/status`] as const;

export type UpdateEssayStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateEssayStatus>>>

export const useUpdateEssayStatus = <TError = Promise<ErrorModel>>(
  essayId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateEssayStatus>>, TError, Key, NonReadonly<UpdateStatusBody>, Awaited<ReturnType<typeof updateEssayStatus>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateEssayStatusMutationKey(essayId);
  const swrFn = getUpdateEssayStatusMutationFetcher(essayId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getEssaysFromStudentResponse200 = {
  data: EssayListBody
  status: 200
}

export type getEssaysFromStudentResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getEssaysFromStudentResponseSuccess = (getEssaysFromStudentResponse200) & {
  headers: Headers;
};
export type getEssaysFromStudentResponseError = (getEssaysFromStudentResponseDefault) & {
  headers: Headers;
};

export type getEssaysFromStudentResponse = (getEssaysFromStudentResponseSuccess | getEssaysFromStudentResponseError)

export const getGetEssaysFromStudentUrl = (studentId: string,) => {




  return `/api/students/${studentId}/essays`
}

/**
 * Shows all essays of a student
 */
export const getEssaysFromStudent = async (studentId: string, options?: RequestInit): Promise<getEssaysFromStudentResponse> => {

  const res = await fetch(getGetEssaysFromStudentUrl(studentId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getEssaysFromStudentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getEssaysFromStudentResponse
}




export const getGetEssaysFromStudentKey = (studentId: string,) => [`/api/students/${studentId}/essays`] as const;

export type GetEssaysFromStudentQueryResult = NonNullable<Awaited<ReturnType<typeof getEssaysFromStudent>>>

export const useGetEssaysFromStudent = <TError = Promise<ErrorModel>>(
  studentId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getEssaysFromStudent>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && studentId !== null && studentId !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetEssaysFromStudentKey(studentId) : null);
  const swrFn = () => getEssaysFromStudent(studentId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
