/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  EssayListBody
} from '../../models';

import {
  getGetEssaysFromStudentResponseMock
} from './essays.faker';

export { getGetEssaysFromStudentResponseMock } from './essays.faker';


export const getCreateEssayMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/essays', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getUpdateEssayStatusMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.patch('*/essays/:essayId/status', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getGetEssaysFromStudentMockHandler = (overrideResponse?: EssayListBody | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<EssayListBody> | EssayListBody), options?: RequestHandlerOptions) => {
  return http.get('*/students/:studentId/essays', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetEssaysFromStudentResponseMock(),
      { status: 200
      })
  }, options)
}
export const getEssaysMock = () => [
  getCreateEssayMockHandler(),
  getUpdateEssayStatusMockHandler(),
  getGetEssaysFromStudentMockHandler()
]
