/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  EssayBody,
  EssayListBody
} from '../../models';


export const getGetEssaysByGroupResponseMock = (overrideResponse: Partial<Extract<EssayListBody, object>> = {}): EssayListBody => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), essays: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({college_id: faker.helpers.arrayElement([faker.number.int(), null]), essay_group_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), id: faker.string.alpha({length: {min: 10, max: 20}}), link_to_content: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.string.alpha({length: {min: 10, max: 20}}), student_id: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}})})), null]), ...overrideResponse})

export const getUpdateEssayGroupResponseMock = (overrideResponse: Partial<Extract<EssayBody, object>> = {}): EssayBody => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), essay: {college_id: faker.helpers.arrayElement([faker.number.int(), null]), essay_group_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), id: faker.string.alpha({length: {min: 10, max: 20}}), link_to_content: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.string.alpha({length: {min: 10, max: 20}}), student_id: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getUpdateEssayStatusResponseMock = (overrideResponse: Partial<Extract<EssayBody, object>> = {}): EssayBody => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), essay: {college_id: faker.helpers.arrayElement([faker.number.int(), null]), essay_group_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), id: faker.string.alpha({length: {min: 10, max: 20}}), link_to_content: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.string.alpha({length: {min: 10, max: 20}}), student_id: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getGetEssaysFromStudentResponseMock = (overrideResponse: Partial<Extract<EssayListBody, object>> = {}): EssayListBody => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), essays: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({college_id: faker.helpers.arrayElement([faker.number.int(), null]), essay_group_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), id: faker.string.alpha({length: {min: 10, max: 20}}), link_to_content: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.string.alpha({length: {min: 10, max: 20}}), student_id: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}})})), null]), ...overrideResponse})

