/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ChatMessage,
  ChatMessagePage,
  ChatSummary,
  CreateChatMessageRequestBody,
  EditChatMessageRequestBody,
  ErrorModel,
  ListChatMessagesParams,
  UpdateChatMessageReadInputBody
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type listChatsResponse200 = {
  data: ChatSummary[] | null
  status: 200
}

export type listChatsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listChatsResponseSuccess = (listChatsResponse200) & {
  headers: Headers;
};
export type listChatsResponseError = (listChatsResponseDefault) & {
  headers: Headers;
};

export type listChatsResponse = (listChatsResponseSuccess | listChatsResponseError)

export const getListChatsUrl = () => {




  return `/api/chats`
}

/**
 * List the current user's conversations with their latest message and unread count, most recent first.
 */
export const listChats = async ( options?: RequestInit): Promise<listChatsResponse> => {

  const res = await fetch(getListChatsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listChatsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listChatsResponse
}




export const getListChatsKey = () => [`/api/chats`] as const;

export type ListChatsQueryResult = NonNullable<Awaited<ReturnType<typeof listChats>>>

export const useListChats = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listChats>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListChatsKey() : null);
  const swrFn = () => listChats(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type listChatMessagesResponse200 = {
  data: ChatMessagePage
  status: 200
}

export type listChatMessagesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listChatMessagesResponseSuccess = (listChatMessagesResponse200) & {
  headers: Headers;
};
export type listChatMessagesResponseError = (listChatMessagesResponseDefault) & {
  headers: Headers;
};

export type listChatMessagesResponse = (listChatMessagesResponseSuccess | listChatMessagesResponseError)

export const getListChatMessagesUrl = (userId: string,
    params?: ListChatMessagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/chats/${userId}/messages?${stringifiedParams}` : `/api/chats/${userId}/messages`
}

/**
 * Get a page of messages between the current user and another user, newest first.
 */
export const listChatMessages = async (userId: string,
    params?: ListChatMessagesParams, options?: RequestInit): Promise<listChatMessagesResponse> => {

  const res = await fetch(getListChatMessagesUrl(userId,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listChatMessagesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listChatMessagesResponse
}




export const getListChatMessagesKey = (userId: string,
    params?: ListChatMessagesParams,) => [`/api/chats/${userId}/messages`, ...(params ? [params]: [])] as const;

export type ListChatMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof listChatMessages>>>

export const useListChatMessages = <TError = Promise<ErrorModel>>(
  userId: string,
    params?: ListChatMessagesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listChatMessages>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && userId !== null && userId !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListChatMessagesKey(userId,params) : null);
  const swrFn = () => listChatMessages(userId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type markChatReadResponse204 = {
  data: void
  status: 204
}

export type markChatReadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type markChatReadResponseSuccess = (markChatReadResponse204) & {
  headers: Headers;
};
export type markChatReadResponseError = (markChatReadResponseDefault) & {
  headers: Headers;
};

export type markChatReadResponse = (markChatReadResponseSuccess | markChatReadResponseError)

export const getMarkChatReadUrl = (userId: string,) => {




  return `/api/chats/${userId}/read`
}

/**
 * Mark every message the other user sent to the current user as read.
 */
export const markChatRead = async (userId: string, options?: RequestInit): Promise<markChatReadResponse> => {

  const res = await fetch(getMarkChatReadUrl(userId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: markChatReadResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as markChatReadResponse
}




export const getMarkChatReadMutationFetcher = (userId: string, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return markChatRead(userId, options);
  }
}
export const getMarkChatReadMutationKey = (userId: string,) => [`/api/chats/${userId}/read`] as const;

export type MarkChatReadMutationResult = NonNullable<Awaited<ReturnType<typeof markChatRead>>>

export const useMarkChatRead = <TError = Promise<ErrorModel>>(
  userId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof markChatRead>>, TError, Key, Arguments, Awaited<ReturnType<typeof markChatRead>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getMarkChatReadMutationKey(userId);
  const swrFn = getMarkChatReadMutationFetcher(userId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type createChatMessageResponse200 = {
  data: ChatMessage
  status: 200
}

export type createChatMessageResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createChatMessageResponseSuccess = (createChatMessageResponse200) & {
  headers: Headers;
};
export type createChatMessageResponseError = (createChatMessageResponseDefault) & {
  headers: Headers;
};

export type createChatMessageResponse = (createChatMessageResponseSuccess | createChatMessageResponseError)

export const getCreateChatMessageUrl = () => {




  return `/api/messages`
}

/**
 * Send a message from the current user to another user.
 */
export const createChatMessage = async (createChatMessageRequestBody: NonReadonly<CreateChatMessageRequestBody>, options?: RequestInit): Promise<createChatMessageResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateChatMessageUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createChatMessageRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createChatMessageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createChatMessageResponse
}




export const getCreateChatMessageMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<CreateChatMessageRequestBody> }) => {
    return createChatMessage(arg, options);
  }
}
export const getCreateChatMessageMutationKey = () => [`/api/messages`] as const;

export type CreateChatMessageMutationResult = NonNullable<Awaited<ReturnType<typeof createChatMessage>>>

export const useCreateChatMessage = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createChatMessage>>, TError, Key, NonReadonly<CreateChatMessageRequestBody>, Awaited<ReturnType<typeof createChatMessage>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateChatMessageMutationKey();
  const swrFn = getCreateChatMessageMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type editChatMessageResponse200 = {
  data: ChatMessage
  status: 200
}

export type editChatMessageResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type editChatMessageResponseSuccess = (editChatMessageResponse200) & {
  headers: Headers;
};
export type editChatMessageResponseError = (editChatMessageResponseDefault) & {
  headers: Headers;
};

export type editChatMessageResponse = (editChatMessageResponseSuccess | editChatMessageResponseError)

export const getEditChatMessageUrl = (id: string,) => {




  return `/api/messages/${id}`
}

/**
 * Edit the text of a message the current user sent.
 */
export const editChatMessage = async (id: string,
    editChatMessageRequestBody: NonReadonly<EditChatMessageRequestBody>, options?: RequestInit): Promise<editChatMessageResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getEditChatMessageUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(editChatMessageRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: editChatMessageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as editChatMessageResponse
}




export const getEditChatMessageMutationFetcher = (id: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<EditChatMessageRequestBody> }) => {
    return editChatMessage(id, arg, options);
  }
}
export const getEditChatMessageMutationKey = (id: string,) => [`/api/messages/${id}`] as const;

export type EditChatMessageMutationResult = NonNullable<Awaited<ReturnType<typeof editChatMessage>>>

export const useEditChatMessage = <TError = Promise<ErrorModel>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof editChatMessage>>, TError, Key, NonReadonly<EditChatMessageRequestBody>, Awaited<ReturnType<typeof editChatMessage>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getEditChatMessageMutationKey(id);
  const swrFn = getEditChatMessageMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type updateChatMessageReadResponse200 = {
  data: ChatMessage
  status: 200
}

export type updateChatMessageReadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateChatMessageReadResponseSuccess = (updateChatMessageReadResponse200) & {
  headers: Headers;
};
export type updateChatMessageReadResponseError = (updateChatMessageReadResponseDefault) & {
  headers: Headers;
};

export type updateChatMessageReadResponse = (updateChatMessageReadResponseSuccess | updateChatMessageReadResponseError)

export const getUpdateChatMessageReadUrl = (id: string,) => {




  return `/api/messages/${id}/read`
}

/**
 * Mark a message the current user received as read or unread.
 */
export const updateChatMessageRead = async (id: string,
    updateChatMessageReadInputBody: NonReadonly<UpdateChatMessageReadInputBody>, options?: RequestInit): Promise<updateChatMessageReadResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getUpdateChatMessageReadUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateChatMessageReadInputBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateChatMessageReadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateChatMessageReadResponse
}




export const getUpdateChatMessageReadMutationFetcher = (id: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<UpdateChatMessageReadInputBody> }) => {
    return updateChatMessageRead(id, arg, options);
  }
}
export const getUpdateChatMessageReadMutationKey = (id: string,) => [`/api/messages/${id}/read`] as const;

export type UpdateChatMessageReadMutationResult = NonNullable<Awaited<ReturnType<typeof updateChatMessageRead>>>

export const useUpdateChatMessageRead = <TError = Promise<ErrorModel>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateChatMessageRead>>, TError, Key, NonReadonly<UpdateChatMessageReadInputBody>, Awaited<ReturnType<typeof updateChatMessageRead>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateChatMessageReadMutationKey(id);
  const swrFn = getUpdateChatMessageReadMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
