/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ChatMessage,
  ChatMessagePage,
  ChatSummary
} from '../../models';

import {
  getCreateChatMessageResponseMock,
  getEditChatMessageResponseMock,
  getListChatMessagesResponseMock,
  getListChatsResponseMock,
  getUpdateChatMessageReadResponseMock
} from './chat.faker';

export { getListChatsResponseMock, getListChatMessagesResponseMock, getCreateChatMessageResponseMock, getEditChatMessageResponseMock, getUpdateChatMessageReadResponseMock } from './chat.faker';


export const getListChatsMockHandler = (overrideResponse?: ChatSummary[] | null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ChatSummary[] | null> | ChatSummary[] | null), options?: RequestHandlerOptions) => {
  return http.get('*/chats', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListChatsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListChatMessagesMockHandler = (overrideResponse?: ChatMessagePage | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ChatMessagePage> | ChatMessagePage), options?: RequestHandlerOptions) => {
  return http.get('*/chats/:userId/messages', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListChatMessagesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getMarkChatReadMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/chats/:userId/read', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getCreateChatMessageMockHandler = (overrideResponse?: ChatMessage | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ChatMessage> | ChatMessage), options?: RequestHandlerOptions) => {
  return http.post('*/messages', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateChatMessageResponseMock(),
      { status: 200
      })
  }, options)
}

export const getEditChatMessageMockHandler = (overrideResponse?: ChatMessage | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ChatMessage> | ChatMessage), options?: RequestHandlerOptions) => {
  return http.patch('*/messages/:id', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getEditChatMessageResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateChatMessageReadMockHandler = (overrideResponse?: ChatMessage | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ChatMessage> | ChatMessage), options?: RequestHandlerOptions) => {
  return http.patch('*/messages/:id/read', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateChatMessageReadResponseMock(),
      { status: 200
      })
  }, options)
}
export const getChatMock = () => [
  getListChatsMockHandler(),
  getListChatMessagesMockHandler(),
  getMarkChatReadMockHandler(),
  getCreateChatMessageMockHandler(),
  getEditChatMessageMockHandler(),
  getUpdateChatMessageReadMockHandler()
]
