/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  ChatMessage,
  ChatMessagePage,
  ChatSummary
} from '../../models';


export const getListChatsResponseMock = (): ChatSummary[] | null => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({last_message: faker.string.alpha({length: {min: 10, max: 20}}), last_message_at: faker.date.past().toISOString().slice(0, 19) + 'Z', last_message_id: faker.string.alpha({length: {min: 10, max: 20}}), last_message_read_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', null]), last_sender_id: faker.string.alpha({length: {min: 10, max: 20}}), other_user_id: faker.string.alpha({length: {min: 10, max: 20}}), other_user_name: faker.string.alpha({length: {min: 10, max: 20}}), other_user_pfp_key: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), unread_count: faker.number.int()})))

export const getListChatMessagesResponseMock = (overrideResponse: Partial<Extract<ChatMessagePage, object>> = {}): ChatMessagePage => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), messages: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', edited_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', null]), id: faker.string.alpha({length: {min: 10, max: 20}}), message: faker.string.alpha({length: {min: 10, max: 20}}), read_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', null]), recipient_id: faker.string.alpha({length: {min: 10, max: 20}}), sender_id: faker.string.alpha({length: {min: 10, max: 20}})})), null]), next_cursor: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), ...overrideResponse})

export const getCreateChatMessageResponseMock = (overrideResponse: Partial<Extract<ChatMessage, object>> = {}): ChatMessage => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', edited_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', null]), id: faker.string.alpha({length: {min: 10, max: 20}}), message: faker.string.alpha({length: {min: 10, max: 20}}), read_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', null]), recipient_id: faker.string.alpha({length: {min: 10, max: 20}}), sender_id: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getEditChatMessageResponseMock = (overrideResponse: Partial<Extract<ChatMessage, object>> = {}): ChatMessage => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', edited_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', null]), id: faker.string.alpha({length: {min: 10, max: 20}}), message: faker.string.alpha({length: {min: 10, max: 20}}), read_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', null]), recipient_id: faker.string.alpha({length: {min: 10, max: 20}}), sender_id: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getUpdateChatMessageReadResponseMock = (overrideResponse: Partial<Extract<ChatMessage, object>> = {}): ChatMessage => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', edited_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', null]), id: faker.string.alpha({length: {min: 10, max: 20}}), message: faker.string.alpha({length: {min: 10, max: 20}}), read_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', null]), recipient_id: faker.string.alpha({length: {min: 10, max: 20}}), sender_id: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

