/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  PresignUploadResponse,
  Video
} from '../../models';

import {
  getGetVideoResponseMock,
  getListVideosResponseMock,
  getUploadVideoResponseMock
} from './videos.faker';

export { getListVideosResponseMock, getUploadVideoResponseMock, getGetVideoResponseMock } from './videos.faker';


export const getListVideosMockHandler = (overrideResponse?: Video[] | null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Video[] | null> | Video[] | null), options?: RequestHandlerOptions) => {
  return http.get('*/videos', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListVideosResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUploadVideoMockHandler = (overrideResponse?: PresignUploadResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PresignUploadResponse> | PresignUploadResponse), options?: RequestHandlerOptions) => {
  return http.post('*/videos', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUploadVideoResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetVideoMockHandler = (overrideResponse?: Video | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Video> | Video), options?: RequestHandlerOptions) => {
  return http.get('*/videos/lookup', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetVideoResponseMock(),
      { status: 200
      })
  }, options)
}
export const getVideosMock = () => [
  getListVideosMockHandler(),
  getUploadVideoMockHandler(),
  getGetVideoMockHandler()
]
