/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ErrorModel,
  GetVideoParams,
  PresignUploadRequestBody,
  PresignUploadResponse,
  Video
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type listVideosResponse200 = {
  data: Video[] | null
  status: 200
}

export type listVideosResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listVideosResponseSuccess = (listVideosResponse200) & {
  headers: Headers;
};
export type listVideosResponseError = (listVideosResponseDefault) & {
  headers: Headers;
};

export type listVideosResponse = (listVideosResponseSuccess | listVideosResponseError)

export const getListVideosUrl = () => {




  return `http://127.0.0.1:8080/videos`
}

/**
 * List all videos in the S3 bucket.
 */
export const listVideos = async ( options?: RequestInit): Promise<listVideosResponse> => {

  const res = await fetch(getListVideosUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listVideosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listVideosResponse
}




export const getListVideosKey = () => [`http://127.0.0.1:8080/videos`] as const;

export type ListVideosQueryResult = NonNullable<Awaited<ReturnType<typeof listVideos>>>

export const useListVideos = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listVideos>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListVideosKey() : null);
  const swrFn = () => listVideos(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type uploadVideoResponse200 = {
  data: PresignUploadResponse
  status: 200
}

export type uploadVideoResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type uploadVideoResponseSuccess = (uploadVideoResponse200) & {
  headers: Headers;
};
export type uploadVideoResponseError = (uploadVideoResponseDefault) & {
  headers: Headers;
};

export type uploadVideoResponse = (uploadVideoResponseSuccess | uploadVideoResponseError)

export const getUploadVideoUrl = () => {




  return `http://127.0.0.1:8080/videos`
}

/**
 * Upload a new video to the S3 bucket.
 */
export const uploadVideo = async (presignUploadRequestBody: NonReadonly<PresignUploadRequestBody>, options?: RequestInit): Promise<uploadVideoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getUploadVideoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(presignUploadRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadVideoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadVideoResponse
}




export const getUploadVideoMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<PresignUploadRequestBody> }) => {
    return uploadVideo(arg, options);
  }
}
export const getUploadVideoMutationKey = () => [`http://127.0.0.1:8080/videos`] as const;

export type UploadVideoMutationResult = NonNullable<Awaited<ReturnType<typeof uploadVideo>>>

export const useUploadVideo = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof uploadVideo>>, TError, Key, NonReadonly<PresignUploadRequestBody>, Awaited<ReturnType<typeof uploadVideo>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUploadVideoMutationKey();
  const swrFn = getUploadVideoMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getVideoResponse200 = {
  data: Video
  status: 200
}

export type getVideoResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getVideoResponseSuccess = (getVideoResponse200) & {
  headers: Headers;
};
export type getVideoResponseError = (getVideoResponseDefault) & {
  headers: Headers;
};

export type getVideoResponse = (getVideoResponseSuccess | getVideoResponseError)

export const getGetVideoUrl = (params?: GetVideoParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://127.0.0.1:8080/videos/lookup?${stringifiedParams}` : `http://127.0.0.1:8080/videos/lookup`
}

/**
 * Get a video by its S3 key.
 */
export const getVideo = async (params?: GetVideoParams, options?: RequestInit): Promise<getVideoResponse> => {

  const res = await fetch(getGetVideoUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getVideoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getVideoResponse
}




export const getGetVideoKey = (params?: GetVideoParams,) => [`http://127.0.0.1:8080/videos/lookup`, ...(params ? [params]: [])] as const;

export type GetVideoQueryResult = NonNullable<Awaited<ReturnType<typeof getVideo>>>

export const useGetVideo = <TError = Promise<ErrorModel>>(
  params?: GetVideoParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getVideo>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetVideoKey(params) : null);
  const swrFn = () => getVideo(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
