/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  PresignUploadResponse,
  Video
} from '../../models';


export const getListVideosResponseMock = (): Video[] | null => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), download_url: faker.string.alpha({length: {min: 10, max: 20}}), s3_key: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getUploadVideoResponseMock = (overrideResponse: Partial<Extract<PresignUploadResponse, object>> = {}): PresignUploadResponse => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), s3_key: faker.string.alpha({length: {min: 10, max: 20}}), upload_url: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getGetVideoResponseMock = (overrideResponse: Partial<Extract<Video, object>> = {}): Video => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), download_url: faker.string.alpha({length: {min: 10, max: 20}}), s3_key: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

