/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ErrorModel,
  EssayReviewStatus,
  EssayReviewTransaction,
  RefundEssayReviewResponseBody,
  RequestEssayReviewRequestBody
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type getEssayReviewStatusResponse200 = {
  data: EssayReviewStatus
  status: 200
}

export type getEssayReviewStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getEssayReviewStatusResponseSuccess = (getEssayReviewStatusResponse200) & {
  headers: Headers;
};
export type getEssayReviewStatusResponseError = (getEssayReviewStatusResponseDefault) & {
  headers: Headers;
};

export type getEssayReviewStatusResponse = (getEssayReviewStatusResponseSuccess | getEssayReviewStatusResponseError)

export const getGetEssayReviewStatusUrl = (essayId: string,) => {




  return `http://127.0.0.1:8080/essays/${essayId}/review-status`
}

/**
 * Get the current review status of an essay, from its most recent review request.
 */
export const getEssayReviewStatus = async (essayId: string, options?: RequestInit): Promise<getEssayReviewStatusResponse> => {

  const res = await fetch(getGetEssayReviewStatusUrl(essayId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getEssayReviewStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getEssayReviewStatusResponse
}




export const getGetEssayReviewStatusKey = (essayId: string,) => [`http://127.0.0.1:8080/essays/${essayId}/review-status`] as const;

export type GetEssayReviewStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getEssayReviewStatus>>>

export const useGetEssayReviewStatus = <TError = Promise<ErrorModel>>(
  essayId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getEssayReviewStatus>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && essayId !== null && essayId !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetEssayReviewStatusKey(essayId) : null);
  const swrFn = () => getEssayReviewStatus(essayId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type requestEssayReviewResponse200 = {
  data: EssayReviewTransaction
  status: 200
}

export type requestEssayReviewResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type requestEssayReviewResponseSuccess = (requestEssayReviewResponse200) & {
  headers: Headers;
};
export type requestEssayReviewResponseError = (requestEssayReviewResponseDefault) & {
  headers: Headers;
};

export type requestEssayReviewResponse = (requestEssayReviewResponseSuccess | requestEssayReviewResponseError)

export const getRequestEssayReviewUrl = () => {




  return `http://127.0.0.1:8080/reviews`
}

/**
 * Spend a student's review balance to open a review on an essay.
 */
export const requestEssayReview = async (requestEssayReviewRequestBody: NonReadonly<RequestEssayReviewRequestBody>, options?: RequestInit): Promise<requestEssayReviewResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getRequestEssayReviewUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(requestEssayReviewRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: requestEssayReviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as requestEssayReviewResponse
}




export const getRequestEssayReviewMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<RequestEssayReviewRequestBody> }) => {
    return requestEssayReview(arg, options);
  }
}
export const getRequestEssayReviewMutationKey = () => [`http://127.0.0.1:8080/reviews`] as const;

export type RequestEssayReviewMutationResult = NonNullable<Awaited<ReturnType<typeof requestEssayReview>>>

export const useRequestEssayReview = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof requestEssayReview>>, TError, Key, NonReadonly<RequestEssayReviewRequestBody>, Awaited<ReturnType<typeof requestEssayReview>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRequestEssayReviewMutationKey();
  const swrFn = getRequestEssayReviewMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type completeEssayReviewResponse200 = {
  data: EssayReviewTransaction
  status: 200
}

export type completeEssayReviewResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type completeEssayReviewResponseSuccess = (completeEssayReviewResponse200) & {
  headers: Headers;
};
export type completeEssayReviewResponseError = (completeEssayReviewResponseDefault) & {
  headers: Headers;
};

export type completeEssayReviewResponse = (completeEssayReviewResponseSuccess | completeEssayReviewResponseError)

export const getCompleteEssayReviewUrl = (id: string,) => {




  return `http://127.0.0.1:8080/reviews/${id}/complete`
}

/**
 * Mark a review as having been completed by a counselor.
 */
export const completeEssayReview = async (id: string, options?: RequestInit): Promise<completeEssayReviewResponse> => {

  const res = await fetch(getCompleteEssayReviewUrl(id),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: completeEssayReviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as completeEssayReviewResponse
}




export const getCompleteEssayReviewMutationFetcher = (id: string, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return completeEssayReview(id, options);
  }
}
export const getCompleteEssayReviewMutationKey = (id: string,) => [`http://127.0.0.1:8080/reviews/${id}/complete`] as const;

export type CompleteEssayReviewMutationResult = NonNullable<Awaited<ReturnType<typeof completeEssayReview>>>

export const useCompleteEssayReview = <TError = Promise<ErrorModel>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof completeEssayReview>>, TError, Key, Arguments, Awaited<ReturnType<typeof completeEssayReview>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCompleteEssayReviewMutationKey(id);
  const swrFn = getCompleteEssayReviewMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type refundEssayReviewResponse200 = {
  data: RefundEssayReviewResponseBody
  status: 200
}

export type refundEssayReviewResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type refundEssayReviewResponseSuccess = (refundEssayReviewResponse200) & {
  headers: Headers;
};
export type refundEssayReviewResponseError = (refundEssayReviewResponseDefault) & {
  headers: Headers;
};

export type refundEssayReviewResponse = (refundEssayReviewResponseSuccess | refundEssayReviewResponseError)

export const getRefundEssayReviewUrl = (id: string,) => {




  return `http://127.0.0.1:8080/reviews/${id}/refund`
}

/**
 * Refund a review that has not been completed, crediting the balance back to the student.
 */
export const refundEssayReview = async (id: string, options?: RequestInit): Promise<refundEssayReviewResponse> => {

  const res = await fetch(getRefundEssayReviewUrl(id),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: refundEssayReviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as refundEssayReviewResponse
}




export const getRefundEssayReviewMutationFetcher = (id: string, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return refundEssayReview(id, options);
  }
}
export const getRefundEssayReviewMutationKey = (id: string,) => [`http://127.0.0.1:8080/reviews/${id}/refund`] as const;

export type RefundEssayReviewMutationResult = NonNullable<Awaited<ReturnType<typeof refundEssayReview>>>

export const useRefundEssayReview = <TError = Promise<ErrorModel>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof refundEssayReview>>, TError, Key, Arguments, Awaited<ReturnType<typeof refundEssayReview>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRefundEssayReviewMutationKey(id);
  const swrFn = getRefundEssayReviewMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
