/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  EssayReviewStatus,
  EssayReviewTransaction,
  RefundEssayReviewResponseBody
} from '../../models';

import {
  getCompleteEssayReviewResponseMock,
  getGetEssayReviewStatusResponseMock,
  getRefundEssayReviewResponseMock,
  getRequestEssayReviewResponseMock
} from './essay-reviews.faker';

export { getGetEssayReviewStatusResponseMock, getRequestEssayReviewResponseMock, getCompleteEssayReviewResponseMock, getRefundEssayReviewResponseMock } from './essay-reviews.faker';


export const getGetEssayReviewStatusMockHandler = (overrideResponse?: EssayReviewStatus | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<EssayReviewStatus> | EssayReviewStatus), options?: RequestHandlerOptions) => {
  return http.get('*/essays/:essayId/review-status', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetEssayReviewStatusResponseMock(),
      { status: 200
      })
  }, options)
}

export const getRequestEssayReviewMockHandler = (overrideResponse?: EssayReviewTransaction | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<EssayReviewTransaction> | EssayReviewTransaction), options?: RequestHandlerOptions) => {
  return http.post('*/reviews', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRequestEssayReviewResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCompleteEssayReviewMockHandler = (overrideResponse?: EssayReviewTransaction | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<EssayReviewTransaction> | EssayReviewTransaction), options?: RequestHandlerOptions) => {
  return http.post('*/reviews/:id/complete', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCompleteEssayReviewResponseMock(),
      { status: 200
      })
  }, options)
}

export const getRefundEssayReviewMockHandler = (overrideResponse?: RefundEssayReviewResponseBody | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<RefundEssayReviewResponseBody> | RefundEssayReviewResponseBody), options?: RequestHandlerOptions) => {
  return http.post('*/reviews/:id/refund', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRefundEssayReviewResponseMock(),
      { status: 200
      })
  }, options)
}
export const getEssayReviewsMock = () => [
  getGetEssayReviewStatusMockHandler(),
  getRequestEssayReviewMockHandler(),
  getCompleteEssayReviewMockHandler(),
  getRefundEssayReviewMockHandler()
]
