/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod/mini';

/**
 * List all college applications for the authenticated student.
 */
export const ListPersonalCollegeApplicationsResponseItem = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "application_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Which deadline the student is applying by: EA, ED, or RD')),
  "category": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('How the student categorizes this school: safety, target, or reach')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "global_college_id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('ID of the global college being applied to')),
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Unique identifier for the application')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the student who owns this application')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true})
})
export const ListPersonalCollegeApplicationsResponse = /*#__PURE__*/ zod.array(ListPersonalCollegeApplicationsResponseItem)


/**
 * Create a personal college application for the authenticated student.
 */
export const CreatePersonalCollegeApplicationBody = /*#__PURE__*/ zod.object({
  "application_type": /*#__PURE__*/ zod.enum(['EA', 'ED', 'RD']).check(/*#__PURE__*/ zod.describe('Which deadline the student is applying by')),
  "category": /*#__PURE__*/ zod.enum(['safety', 'target', 'reach']).check(/*#__PURE__*/ zod.describe('How the student categorizes this school')),
  "global_college_id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('ID of the global college being applied to'))
})

export const CreatePersonalCollegeApplicationResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "application_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Which deadline the student is applying by: EA, ED, or RD')),
  "category": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('How the student categorizes this school: safety, target, or reach')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "global_college_id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('ID of the global college being applied to')),
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Unique identifier for the application')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the student who owns this application')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true})
})


/**
 * List the current user's conversations with their latest message and unread count, most recent first.
 */
export const ListChatsResponseItem = /*#__PURE__*/ zod.object({
  "last_message": /*#__PURE__*/ zod.string(),
  "last_message_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "last_message_id": /*#__PURE__*/ zod.string(),
  "last_message_read_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "last_sender_id": /*#__PURE__*/ zod.string(),
  "other_user_id": /*#__PURE__*/ zod.string(),
  "other_user_name": /*#__PURE__*/ zod.string(),
  "other_user_pfp_key": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "unread_count": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Messages from the other user the current user has not read'))
})
export const ListChatsResponse = /*#__PURE__*/ zod.array(ListChatsResponseItem)


/**
 * Get a page of messages between the current user and another user, newest first.
 */
export const ListChatMessagesParams = /*#__PURE__*/ zod.object({
  "user_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('The other user in the conversation'))
})

export const listChatMessagesQueryLimitDefault = 50;
export const listChatMessagesQueryLimitMax = 100;



export const ListChatMessagesQueryParams = /*#__PURE__*/ zod.object({
  "cursor": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('next_cursor from the previous page; omit to get the newest messages')),
  "limit": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(1)).check(/*#__PURE__*/ zod.lte(listChatMessagesQueryLimitMax)), listChatMessagesQueryLimitDefault)
})

export const ListChatMessagesResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "messages": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.array(/*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "edited_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Null if the message was never edited')),
  "id": /*#__PURE__*/ zod.string(),
  "message": /*#__PURE__*/ zod.string(),
  "read_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Null if the recipient has not read the message')),
  "recipient_id": /*#__PURE__*/ zod.string(),
  "sender_id": /*#__PURE__*/ zod.string()
}))).check(/*#__PURE__*/ zod.describe('Newest first')),
  "next_cursor": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Pass as cursor to get older messages; null when there are none'))
})


/**
 * Mark every message the other user sent to the current user as read.
 */
export const MarkChatReadParams = /*#__PURE__*/ zod.object({
  "user_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('The other user in the conversation'))
})

export const MarkChatReadResponse = /*#__PURE__*/ zod.void()


/**
 * List all global colleges.
 */
export const ListGlobalCollegesResponseItem = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was created')),
  "ea_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early admission deadline')),
  "ed_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early decision deadline')),
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Unique identifier for the college')),
  "rd_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Regular decision deadline')),
  "school_location": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Location of the college')),
  "school_name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Name of the college')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was last updated'))
})
export const ListGlobalCollegesResponse = /*#__PURE__*/ zod.array(ListGlobalCollegesResponseItem)


/**
 * Create a global college with a name, location, and optional EA/ED/RD deadlines.
 */
export const CreateGlobalCollegeBody = /*#__PURE__*/ zod.object({
  "ea_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early admission deadline')),
  "ed_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early decision deadline')),
  "rd_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Regular decision deadline')),
  "school_location": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Location of the college')),
  "school_name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Name of the college'))
})

export const CreateGlobalCollegeResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was created')),
  "ea_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early admission deadline')),
  "ed_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early decision deadline')),
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Unique identifier for the college')),
  "rd_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Regular decision deadline')),
  "school_location": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Location of the college')),
  "school_name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Name of the college')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was last updated'))
})


/**
 * Get a global college by ID.
 */
export const GetGlobalCollegeParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.int()
})

export const GetGlobalCollegeResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was created')),
  "ea_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early admission deadline')),
  "ed_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early decision deadline')),
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Unique identifier for the college')),
  "rd_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Regular decision deadline')),
  "school_location": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Location of the college')),
  "school_name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Name of the college')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was last updated'))
})


/**
 * Creates an essay group for a student
 */
export const createEssayGroupBodyNameMax = 100;



export const CreateEssayGroupBody = /*#__PURE__*/ zod.object({
  "description": /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Optional description of the group')),
  "name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)).check(/*#__PURE__*/ zod.maxLength(createEssayGroupBodyNameMax)).check(/*#__PURE__*/ zod.describe('Unique name for the group')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student the group belongs to'))
})

export const CreateEssayGroupResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "description": /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
  "id": /*#__PURE__*/ zod.string(),
  "name": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string()
})


/**
 * Shows all essays belonging to an essay group
 */
export const GetEssaysByGroupParams = /*#__PURE__*/ zod.object({
  "essay_group_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Group whose essays to list'))
})

export const GetEssaysByGroupResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "essays": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.array(/*#__PURE__*/ zod.object({
  "college_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "essay_group_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "id": /*#__PURE__*/ zod.string(),
  "link_to_content": /*#__PURE__*/ zod.string(),
  "status": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string(),
  "type": /*#__PURE__*/ zod.string()
})))
})


/**
 * Creates an essay with the logged in student
 */
export const createEssayBodyLinkToContentMin = 10;

export const createEssayBodyTypeMax = 100;



export const CreateEssayBody = /*#__PURE__*/ zod.object({
  "college_id": /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.int()).check(/*#__PURE__*/ zod.describe('Optional college this essay targets')),
  "essay_group_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('optional group this essay belongs to')),
  "link_to_content": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(createEssayBodyLinkToContentMin)),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student the essay belongs to')),
  "type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.maxLength(createEssayBodyTypeMax))
})

export const CreateEssayResponse = /*#__PURE__*/ zod.void()


/**
 * Adds an essay to a group, moves it to another group, or removes it from its group
 */
export const UpdateEssayGroupParams = /*#__PURE__*/ zod.object({
  "essay_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Essay to move'))
})

export const UpdateEssayGroupBody = /*#__PURE__*/ zod.object({
  "essay_group_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Group to move the essay into, or null to remove it from its group'))
})

export const UpdateEssayGroupResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "essay": /*#__PURE__*/ zod.object({
  "college_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "essay_group_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "id": /*#__PURE__*/ zod.string(),
  "link_to_content": /*#__PURE__*/ zod.string(),
  "status": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string(),
  "type": /*#__PURE__*/ zod.string()
})
})


/**
 * Get the current review status of an essay, from its most recent review request.
 */
export const GetEssayReviewStatusParams = /*#__PURE__*/ zod.object({
  "essay_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the essay to look up'))
})

export const GetEssayReviewStatusResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('When a counselor completed it')),
  "essay_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Essay the review is for')),
  "requested_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('When the review was requested')),
  "status": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('open, completed, or refunded')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student who requested the review')),
  "transaction_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Ledger row this status came from'))
})


/**
 * updates the status of a students essay
 */
export const UpdateEssayStatusParams = /*#__PURE__*/ zod.object({
  "essay_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Essay to update'))
})

export const UpdateEssayStatusBody = /*#__PURE__*/ zod.object({
  "status": /*#__PURE__*/ zod.enum(['Submitted', 'Draft', 'Review', 'Archived']).check(/*#__PURE__*/ zod.describe('New status for the essay'))
})

export const UpdateEssayStatusResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "essay": /*#__PURE__*/ zod.object({
  "college_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "essay_group_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "id": /*#__PURE__*/ zod.string(),
  "link_to_content": /*#__PURE__*/ zod.string(),
  "status": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string(),
  "type": /*#__PURE__*/ zod.string()
})
})


/**
 * List extracurriculars for the authenticated student.
 */
export const ListExtracurricularsResponseItem = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "description": /*#__PURE__*/ zod.string(),
  "end_date": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "id": /*#__PURE__*/ zod.int(),
  "leadership_role": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "modified_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "name": /*#__PURE__*/ zod.string(),
  "organization": /*#__PURE__*/ zod.string(),
  "start_date": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "status": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string(),
  "type": /*#__PURE__*/ zod.string(),
  "user_id": /*#__PURE__*/ zod.string()
})
export const ListExtracurricularsResponse = /*#__PURE__*/ zod.array(ListExtracurricularsResponseItem)


/**
 * Update fields on an extracurricular for the authenticated student.
 */
export const UpdateExtracurricularParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('ID of the extracurricular to update'))
})




export const UpdateExtracurricularBody = /*#__PURE__*/ zod.object({
  "description": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "end_date": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.date()),
  "leadership_role": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "name": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1))),
  "organization": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "start_date": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.date()),
  "status": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.enum(['doing', 'have_done'])),
  "type": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.enum(['maintenance', 'investment']))
})

export const UpdateExtracurricularResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "description": /*#__PURE__*/ zod.string(),
  "end_date": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "id": /*#__PURE__*/ zod.int(),
  "leadership_role": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "modified_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "name": /*#__PURE__*/ zod.string(),
  "organization": /*#__PURE__*/ zod.string(),
  "start_date": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "status": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string(),
  "type": /*#__PURE__*/ zod.string(),
  "user_id": /*#__PURE__*/ zod.string()
})


/**
 * Create a new extracurricular for the given student.
 */
export const CreateExtracurricularParams = /*#__PURE__*/ zod.object({
  "studentID": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the student the extracurricular belongs to'))
})




export const CreateExtracurricularBody = /*#__PURE__*/ zod.object({
  "description": /*#__PURE__*/ zod.string(),
  "end_date": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.date()),
  "leadership_role": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  "organization": /*#__PURE__*/ zod.string(),
  "start_date": /*#__PURE__*/ zod.iso.date(),
  "status": /*#__PURE__*/ zod.enum(['doing', 'have_done']),
  "type": /*#__PURE__*/ zod.enum(['maintenance', 'investment'])
})

export const CreateExtracurricularResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "description": /*#__PURE__*/ zod.string(),
  "end_date": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "id": /*#__PURE__*/ zod.int(),
  "leadership_role": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "modified_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "name": /*#__PURE__*/ zod.string(),
  "organization": /*#__PURE__*/ zod.string(),
  "start_date": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "status": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string(),
  "type": /*#__PURE__*/ zod.string(),
  "user_id": /*#__PURE__*/ zod.string()
})


/**
 * Create a greeting for a person by name.
 */
export const createGreetingBodyNameMax = 30;



export const CreateGreetingBody = /*#__PURE__*/ zod.object({
  "name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.maxLength(createGreetingBodyNameMax)).check(/*#__PURE__*/ zod.describe('Name to greet'))
})

export const CreateGreetingResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "greeting": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Greeting message'))
})


/**
 * Fetch all videos, through counselor view
 */
export const listMediaQueryLimitDefault = 20;
export const listMediaQueryLimitMax = 100;

export const listMediaQueryOffsetDefault = 0;
export const listMediaQueryOffsetMin = 0;



export const ListMediaQueryParams = /*#__PURE__*/ zod.object({
  "limit": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(1)).check(/*#__PURE__*/ zod.lte(listMediaQueryLimitMax)), listMediaQueryLimitDefault).check(/*#__PURE__*/ zod.describe('Maximum number of media to return')),
  "offset": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(listMediaQueryOffsetMin)), listMediaQueryOffsetDefault).check(/*#__PURE__*/ zod.describe('Number of media to skip before returning results'))
})

export const ListMediaResponseItem = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "description": /*#__PURE__*/ zod.string(),
  "id": /*#__PURE__*/ zod.string(),
  "length_in_mins": /*#__PURE__*/ zod.int(),
  "s3_key": /*#__PURE__*/ zod.string(),
  "school_year": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "title": /*#__PURE__*/ zod.string()
})
export const ListMediaResponse = /*#__PURE__*/ zod.array(ListMediaResponseItem)


/**
 * Create a media/video
 */
export const CreateMediaBody = /*#__PURE__*/ zod.object({
  "description": /*#__PURE__*/ zod.string(),
  "length_in_mins": /*#__PURE__*/ zod.int(),
  "s3_key": /*#__PURE__*/ zod.string(),
  "school_year": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "title": /*#__PURE__*/ zod.string()
})

export const CreateMediaResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "description": /*#__PURE__*/ zod.string(),
  "id": /*#__PURE__*/ zod.string(),
  "length_in_mins": /*#__PURE__*/ zod.int(),
  "s3_key": /*#__PURE__*/ zod.string(),
  "school_year": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "title": /*#__PURE__*/ zod.string()
})


/**
 * Allow students to fetch only videos they have access to
 */
export const getMediaAccessQueryLimitDefault = 20;
export const getMediaAccessQueryLimitMax = 100;

export const getMediaAccessQueryOffsetDefault = 0;
export const getMediaAccessQueryOffsetMin = 0;



export const GetMediaAccessQueryParams = /*#__PURE__*/ zod.object({
  "limit": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(1)).check(/*#__PURE__*/ zod.lte(getMediaAccessQueryLimitMax)), getMediaAccessQueryLimitDefault).check(/*#__PURE__*/ zod.describe('Maximum number of media to return')),
  "offset": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(getMediaAccessQueryOffsetMin)), getMediaAccessQueryOffsetDefault).check(/*#__PURE__*/ zod.describe('Number of media to skip before returning results'))
})

export const GetMediaAccessResponseItem = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "description": /*#__PURE__*/ zod.string(),
  "id": /*#__PURE__*/ zod.string(),
  "length_in_mins": /*#__PURE__*/ zod.int(),
  "s3_key": /*#__PURE__*/ zod.string(),
  "school_year": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "title": /*#__PURE__*/ zod.string()
})
export const GetMediaAccessResponse = /*#__PURE__*/ zod.array(GetMediaAccessResponseItem)


/**
 * Allow a counselor to give a student access to a video
 */
export const CreateMediaAccessBody = /*#__PURE__*/ zod.object({
  "media_id": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string()
})

export const CreateMediaAccessResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "id": /*#__PURE__*/ zod.string(),
  "media_id": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string()
})


/**
 * Allow a counselor to revoke a student access to a video
 */
export const DeleteMediaAccessParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string()
})

export const DeleteMediaAccessResponse = /*#__PURE__*/ zod.void()


/**
 * Delete a video, through counselor view
 */
export const DeleteMediaParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string()
})

export const DeleteMediaResponse = /*#__PURE__*/ zod.void()


/**
 * Get a media/video
 */
export const GetMediaParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string()
})

export const GetMediaResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "description": /*#__PURE__*/ zod.string(),
  "id": /*#__PURE__*/ zod.string(),
  "length_in_mins": /*#__PURE__*/ zod.int(),
  "s3_key": /*#__PURE__*/ zod.string(),
  "school_year": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "title": /*#__PURE__*/ zod.string()
})


/**
 * Send a message from the current user to another user.
 */



export const CreateChatMessageBody = /*#__PURE__*/ zod.object({
  "message": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)).check(/*#__PURE__*/ zod.describe('Message text')),
  "recipient_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('User ID of the message recipient'))
})

export const CreateChatMessageResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "edited_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Null if the message was never edited')),
  "id": /*#__PURE__*/ zod.string(),
  "message": /*#__PURE__*/ zod.string(),
  "read_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Null if the recipient has not read the message')),
  "recipient_id": /*#__PURE__*/ zod.string(),
  "sender_id": /*#__PURE__*/ zod.string()
})


/**
 * Edit the text of a message the current user sent.
 */
export const EditChatMessageParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string()
})




export const EditChatMessageBody = /*#__PURE__*/ zod.object({
  "message": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)).check(/*#__PURE__*/ zod.describe('New message text'))
})

export const EditChatMessageResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "edited_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Null if the message was never edited')),
  "id": /*#__PURE__*/ zod.string(),
  "message": /*#__PURE__*/ zod.string(),
  "read_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Null if the recipient has not read the message')),
  "recipient_id": /*#__PURE__*/ zod.string(),
  "sender_id": /*#__PURE__*/ zod.string()
})


/**
 * Mark a message the current user received as read or unread.
 */
export const UpdateChatMessageReadParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string()
})

export const UpdateChatMessageReadBody = /*#__PURE__*/ zod.object({
  "read": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('False marks the message as unread'))
})

export const UpdateChatMessageReadResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "edited_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Null if the message was never edited')),
  "id": /*#__PURE__*/ zod.string(),
  "message": /*#__PURE__*/ zod.string(),
  "read_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Null if the recipient has not read the message')),
  "recipient_id": /*#__PURE__*/ zod.string(),
  "sender_id": /*#__PURE__*/ zod.string()
})


/**
 * Get notification preferences for the authenticated user.
 */
export const GetNotificationPreferencesResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "days_before_due": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Number of days before the due date to send notifications')),
  "due_date_notifications_enabled": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive due date notifications')),
  "email_enabled": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive email notifications')),
  "notify_past_due": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive notifications for past due dates')),
  "user_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the user who owns this notification preference')),
  "weekly_summary_enabled": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive weekly summary notifications'))
})


/**
 * Update notification preferences for the authenticated user.
 */
export const UpdateNotificationPreferencesBody = /*#__PURE__*/ zod.object({
  "days_before_due": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Number of days before the due date to send notifications')),
  "due_date_notifications_enabled": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive due date notifications')),
  "email_enabled": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive email notifications')),
  "notify_past_due": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive notifications for past due dates')),
  "weekly_summary_enabled": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive weekly summary notifications'))
})

export const UpdateNotificationPreferencesResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "days_before_due": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Number of days before the due date to send notifications')),
  "due_date_notifications_enabled": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive due date notifications')),
  "email_enabled": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive email notifications')),
  "notify_past_due": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive notifications for past due dates')),
  "user_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the user who owns this notification preference')),
  "weekly_summary_enabled": /*#__PURE__*/ zod.boolean().check(/*#__PURE__*/ zod.describe('Whether the user wants to receive weekly summary notifications'))
})


/**
 * Spend a student's review balance to open a review on an essay.
 */
export const requestEssayReviewBodyAmountDefault = 1;



export const RequestEssayReviewBody = /*#__PURE__*/ zod.object({
  "amount": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(1)), requestEssayReviewBodyAmountDefault).check(/*#__PURE__*/ zod.describe('Number of review credits to spend. Positive; recorded on the ledger as a negative subtotal.')),
  "essay_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Essay to review')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student requesting the review'))
})

export const RequestEssayReviewResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "actor_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('User who caused the movement. Null until auth provides the caller.')),
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('When a counselor marked the review complete')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was created')),
  "entry_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Kind of movement: spend, refund, or adjustment')),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Essay under review. Null for an adjustment.')),
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Unique identifier for the transaction')),
  "refund": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('The negative row that reversed this charge, if it was refunded')),
  "status": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Lifecycle of a spend: open, completed, or refunded. Null for refund and adjustment rows.')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student whose balance moved')),
  "subtotal": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Signed change to the student\'s balance. Negative for a spend, positive for a refund or grant. Sums to the balance.')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was last updated'))
})


/**
 * Mark a review as having been completed by a counselor.
 */
export const CompleteEssayReviewParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the review to mark complete'))
})

export const CompleteEssayReviewResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "actor_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('User who caused the movement. Null until auth provides the caller.')),
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('When a counselor marked the review complete')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was created')),
  "entry_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Kind of movement: spend, refund, or adjustment')),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Essay under review. Null for an adjustment.')),
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Unique identifier for the transaction')),
  "refund": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('The negative row that reversed this charge, if it was refunded')),
  "status": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Lifecycle of a spend: open, completed, or refunded. Null for refund and adjustment rows.')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student whose balance moved')),
  "subtotal": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Signed change to the student\'s balance. Negative for a spend, positive for a refund or grant. Sums to the balance.')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was last updated'))
})


/**
 * Refund a review that has not been completed, crediting the balance back to the student.
 */
export const RefundEssayReviewParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the charge to refund'))
})

export const RefundEssayReviewResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "refund": /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "actor_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('User who caused the movement. Null until auth provides the caller.')),
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('When a counselor marked the review complete')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was created')),
  "entry_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Kind of movement: spend, refund, or adjustment')),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Essay under review. Null for an adjustment.')),
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Unique identifier for the transaction')),
  "refund": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('The negative row that reversed this charge, if it was refunded')),
  "status": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Lifecycle of a spend: open, completed, or refunded. Null for refund and adjustment rows.')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student whose balance moved')),
  "subtotal": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Signed change to the student\'s balance. Negative for a spend, positive for a refund or grant. Sums to the balance.')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was last updated'))
}).check(/*#__PURE__*/ zod.describe('The negative row that reversed the charge')),
  "transaction": /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "actor_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('User who caused the movement. Null until auth provides the caller.')),
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('When a counselor marked the review complete')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was created')),
  "entry_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Kind of movement: spend, refund, or adjustment')),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Essay under review. Null for an adjustment.')),
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Unique identifier for the transaction')),
  "refund": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('The negative row that reversed this charge, if it was refunded')),
  "status": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Lifecycle of a spend: open, completed, or refunded. Null for refund and adjustment rows.')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student whose balance moved')),
  "subtotal": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Signed change to the student\'s balance. Negative for a spend, positive for a refund or grant. Sums to the balance.')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was last updated'))
}).check(/*#__PURE__*/ zod.describe('The original charge, now marked refunded'))
})


/**
 * Overwrite a student's review balance with an absolute value, recording the change in the review ledger.
 */
export const SetStudentReviewBalanceParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the student'))
})

export const setStudentReviewBalanceBodyReviewBalanceMin = 0;



export const SetStudentReviewBalanceBody = /*#__PURE__*/ zod.object({
  "review_balance": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(setStudentReviewBalanceBodyReviewBalanceMin)).check(/*#__PURE__*/ zod.describe('Absolute value to set the student\'s review balance to'))
})

export const SetStudentReviewBalanceResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "counselor_id": /*#__PURE__*/ zod.string(),
  "gpa": /*#__PURE__*/ zod.int(),
  "id": /*#__PURE__*/ zod.string(),
  "organization": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "review_balance": /*#__PURE__*/ zod.int(),
  "user_id": /*#__PURE__*/ zod.string(),
  "year": /*#__PURE__*/ zod.string()
})


/**
 * Shows all essay groups of a student
 */
export const GetEssayGroupsFromStudentParams = /*#__PURE__*/ zod.object({
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student whose essay groups to list'))
})

export const GetEssayGroupsFromStudentResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "essay_groups": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.array(/*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "description": /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
  "id": /*#__PURE__*/ zod.string(),
  "name": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string()
})))
})


/**
 * Shows all essays of a student
 */
export const GetEssaysFromStudentParams = /*#__PURE__*/ zod.object({
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student whose essays to list'))
})

export const GetEssaysFromStudentResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "essays": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.array(/*#__PURE__*/ zod.object({
  "college_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "essay_group_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "id": /*#__PURE__*/ zod.string(),
  "link_to_content": /*#__PURE__*/ zod.string(),
  "status": /*#__PURE__*/ zod.string(),
  "student_id": /*#__PURE__*/ zod.string(),
  "type": /*#__PURE__*/ zod.string()
})))
})


/**
 * Get a student's to-do items, with optional filters, sorting, and cursor pagination
 */
export const getTodoItemsQueryStatusDefault = `all`;
export const getTodoItemsQuerySortByDefault = `created_at`;
export const getTodoItemsQuerySortOrderDefault = `desc`;
export const getTodoItemsQueryLimitDefault = 20;
export const getTodoItemsQueryLimitMax = 100;



export const GetTodoItemsQueryParams = /*#__PURE__*/ zod.object({
  "student_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.uuid()).check(/*#__PURE__*/ zod.describe('Student whose to-do items to return; defaults to the authenticated student')),
  "status": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['all', 'completed', 'incomplete']), getTodoItemsQueryStatusDefault).check(/*#__PURE__*/ zod.describe('Filter by completion status')),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.uuid()).check(/*#__PURE__*/ zod.describe('Only return items linked to this essay')),
  "media_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.uuid()).check(/*#__PURE__*/ zod.describe('Only return items linked to this media')),
  "global_college_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.int()).check(/*#__PURE__*/ zod.describe('Only return items linked to this college')),
  "linked_to": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.enum(['essay', 'media', 'college'])).check(/*#__PURE__*/ zod.describe('Only return items linked to any item of this type')),
  "sort_by": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['created_at', 'deadline', 'completed_at', 'updated_at']), getTodoItemsQuerySortByDefault).check(/*#__PURE__*/ zod.describe('Field to sort by')),
  "sort_order": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['asc', 'desc']), getTodoItemsQuerySortOrderDefault).check(/*#__PURE__*/ zod.describe('Sort direction')),
  "cursor": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('next_cursor from the previous page; omit to get the first page')),
  "limit": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(1)).check(/*#__PURE__*/ zod.lte(getTodoItemsQueryLimitMax)), getTodoItemsQueryLimitDefault).check(/*#__PURE__*/ zod.describe('Maximum number of to-do items to return'))
})

export const GetTodoItemsResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "items": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.array(/*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "completed_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "deadline": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "essay_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "global_college_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "id": /*#__PURE__*/ zod.string(),
  "media_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "student_id": /*#__PURE__*/ zod.string(),
  "todo_description": /*#__PURE__*/ zod.string(),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "user_id": /*#__PURE__*/ zod.string()
}))),
  "next_cursor": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Pass as cursor to get the next page; null when there are none'))
})


/**
 * Create a to-do item with a description and optional deadline
 */
export const CreateTodoItemBody = /*#__PURE__*/ zod.object({
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.uuid()).check(/*#__PURE__*/ zod.describe('Essay this task is for; at most one of essay_id, media_id, global_college_id')),
  "global_college_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.int()).check(/*#__PURE__*/ zod.describe('College this task is for; at most one of essay_id, media_id, global_college_id')),
  "media_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.uuid()).check(/*#__PURE__*/ zod.describe('Media this task is for; at most one of essay_id, media_id, global_college_id')),
  "student_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  "todo_description": /*#__PURE__*/ zod.string(),
  "user_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string())
})

export const CreateTodoItemResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "completed_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "deadline": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "essay_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "global_college_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "id": /*#__PURE__*/ zod.string(),
  "media_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "student_id": /*#__PURE__*/ zod.string(),
  "todo_description": /*#__PURE__*/ zod.string(),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "user_id": /*#__PURE__*/ zod.string()
})


/**
 * Search a student's to-do items by description, with the same filters as listing
 */
export const searchTodoItemsQueryStatusDefault = `all`;
export const searchTodoItemsQuerySortByDefault = `created_at`;
export const searchTodoItemsQuerySortOrderDefault = `desc`;
export const searchTodoItemsQueryQMax = 200;

export const searchTodoItemsQueryLimitDefault = 10;
export const searchTodoItemsQueryLimitMax = 50;



export const SearchTodoItemsQueryParams = /*#__PURE__*/ zod.object({
  "student_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.uuid()).check(/*#__PURE__*/ zod.describe('Student whose to-do items to return; defaults to the authenticated student')),
  "status": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['all', 'completed', 'incomplete']), searchTodoItemsQueryStatusDefault).check(/*#__PURE__*/ zod.describe('Filter by completion status')),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.uuid()).check(/*#__PURE__*/ zod.describe('Only return items linked to this essay')),
  "media_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.uuid()).check(/*#__PURE__*/ zod.describe('Only return items linked to this media')),
  "global_college_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.int()).check(/*#__PURE__*/ zod.describe('Only return items linked to this college')),
  "linked_to": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.enum(['essay', 'media', 'college'])).check(/*#__PURE__*/ zod.describe('Only return items linked to any item of this type')),
  "sort_by": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['created_at', 'deadline', 'completed_at', 'updated_at']), searchTodoItemsQuerySortByDefault).check(/*#__PURE__*/ zod.describe('Field to sort by')),
  "sort_order": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['asc', 'desc']), searchTodoItemsQuerySortOrderDefault).check(/*#__PURE__*/ zod.describe('Sort direction')),
  "q": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)).check(/*#__PURE__*/ zod.maxLength(searchTodoItemsQueryQMax)).check(/*#__PURE__*/ zod.describe('Text to search for in to-do descriptions')),
  "cursor": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('next_cursor from the previous page; omit to get the first page')),
  "limit": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(1)).check(/*#__PURE__*/ zod.lte(searchTodoItemsQueryLimitMax)), searchTodoItemsQueryLimitDefault).check(/*#__PURE__*/ zod.describe('Maximum number of to-do items to return'))
})

export const SearchTodoItemsResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "items": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.array(/*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "completed_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "deadline": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "essay_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "global_college_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "id": /*#__PURE__*/ zod.string(),
  "media_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "student_id": /*#__PURE__*/ zod.string(),
  "todo_description": /*#__PURE__*/ zod.string(),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "user_id": /*#__PURE__*/ zod.string()
}))),
  "next_cursor": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Pass as cursor to get the next page; null when there are none'))
})


/**
 * Update a to-do item's completion status
 */
export const UpdateTodoItemCompletedParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string()
})

export const UpdateTodoItemCompletedBody = /*#__PURE__*/ zod.object({
  "completed": /*#__PURE__*/ zod.boolean()
})

export const UpdateTodoItemCompletedResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "completed_at": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "deadline": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.iso.datetime({"offset":true})),
  "essay_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "global_college_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.int()),
  "id": /*#__PURE__*/ zod.string(),
  "media_id": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "student_id": /*#__PURE__*/ zod.string(),
  "todo_description": /*#__PURE__*/ zod.string(),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "user_id": /*#__PURE__*/ zod.string()
})


/**
 * Create a user (student/counselor)
 */
export const createUserBodyNameMax = 200;



export const CreateUserBody = /*#__PURE__*/ zod.object({
  "email": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('email of user for supabase signup')),
  "name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)).check(/*#__PURE__*/ zod.maxLength(createUserBodyNameMax)).check(/*#__PURE__*/ zod.describe('Name of the user')),
  "password": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('password of user for supabase signup')),
  "pfp_key": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('pfp key of user'))
})

export const CreateUserResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "id": /*#__PURE__*/ zod.string(),
  "name": /*#__PURE__*/ zod.string(),
  "needs_to_reset": /*#__PURE__*/ zod.boolean(),
  "pfp_key": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "supabase_id": /*#__PURE__*/ zod.string()
})


/**
 * fetch a user (student/counselor)
 */
export const FetchUserParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string()
})

export const FetchUserResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "id": /*#__PURE__*/ zod.string(),
  "name": /*#__PURE__*/ zod.string(),
  "needs_to_reset": /*#__PURE__*/ zod.boolean(),
  "pfp_key": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "supabase_id": /*#__PURE__*/ zod.string()
})


/**
 * List all videos in the S3 bucket.
 */
export const ListVideosResponseItem = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "download_url": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('A presigned, time-limited URL for playback. Re-fetch this endpoint if the URL expires.')),
  "s3_key": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('The video\'s S3 object key/path, e.g. video-bucket/common-app-tips.mp4'))
})
export const ListVideosResponse = /*#__PURE__*/ zod.array(ListVideosResponseItem)


/**
 * Upload a new video to the S3 bucket.
 */
export const UploadVideoBody = /*#__PURE__*/ zod.object({
  "original_filename": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('The filename of the video about to be uploaded'))
})

export const UploadVideoResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "s3_key": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('The S3 key/path to store elsewhere, e.g. in a media table')),
  "upload_url": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('A presigned URL the client PUTs the raw video bytes to'))
})


/**
 * Get a video by its S3 key.
 */
export const GetVideoQueryParams = /*#__PURE__*/ zod.object({
  "s3_key": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('The S3 key/path of the video to fetch'))
})

export const GetVideoResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "download_url": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('A presigned, time-limited URL for playback. Re-fetch this endpoint if the URL expires.')),
  "s3_key": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('The video\'s S3 object key/path, e.g. video-bucket/common-app-tips.mp4'))
})
