/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod/mini';

/**
 * List all college applications for the authenticated student.
 */
export const ListPersonalCollegeApplicationsResponseItem = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "application_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Which deadline the student is applying by: EA, ED, or RD')),
  "category": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('How the student categorizes this school: safety, target, or reach')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "global_college_id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('ID of the global college being applied to')),
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Unique identifier for the application')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the student who owns this application')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true})
})
export const ListPersonalCollegeApplicationsResponse = /*#__PURE__*/ zod.array(ListPersonalCollegeApplicationsResponseItem)


/**
 * Create a personal college application for the authenticated student.
 */
export const CreatePersonalCollegeApplicationBody = /*#__PURE__*/ zod.object({
  "application_type": /*#__PURE__*/ zod.enum(['EA', 'ED', 'RD']).check(/*#__PURE__*/ zod.describe('Which deadline the student is applying by')),
  "category": /*#__PURE__*/ zod.enum(['safety', 'target', 'reach']).check(/*#__PURE__*/ zod.describe('How the student categorizes this school')),
  "global_college_id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('ID of the global college being applied to'))
})

export const CreatePersonalCollegeApplicationResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "application_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Which deadline the student is applying by: EA, ED, or RD')),
  "category": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('How the student categorizes this school: safety, target, or reach')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "global_college_id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('ID of the global college being applied to')),
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Unique identifier for the application')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the student who owns this application')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true})
})


/**
 * List all global colleges.
 */
export const ListGlobalCollegesResponseItem = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was created')),
  "ea_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early admission deadline')),
  "ed_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early decision deadline')),
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Unique identifier for the college')),
  "rd_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Regular decision deadline')),
  "school_location": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Location of the college')),
  "school_name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Name of the college')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was last updated'))
})
export const ListGlobalCollegesResponse = /*#__PURE__*/ zod.array(ListGlobalCollegesResponseItem)


/**
 * Create a global college with a name, location, and optional EA/ED/RD deadlines.
 */
export const CreateGlobalCollegeBody = /*#__PURE__*/ zod.object({
  "ea_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early admission deadline')),
  "ed_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early decision deadline')),
  "rd_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Regular decision deadline')),
  "school_location": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Location of the college')),
  "school_name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Name of the college'))
})

export const CreateGlobalCollegeResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was created')),
  "ea_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early admission deadline')),
  "ed_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early decision deadline')),
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Unique identifier for the college')),
  "rd_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Regular decision deadline')),
  "school_location": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Location of the college')),
  "school_name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Name of the college')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was last updated'))
})


/**
 * Get a global college by ID.
 */
export const GetGlobalCollegeParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.int()
})

export const GetGlobalCollegeResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was created')),
  "ea_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early admission deadline')),
  "ed_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Early decision deadline')),
  "id": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Unique identifier for the college')),
  "rd_deadline": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('Regular decision deadline')),
  "school_location": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Location of the college')),
  "school_name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Name of the college')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the college was last updated'))
})


/**
 * Get the current review status of an essay, from its most recent review request.
 */
export const GetEssayReviewStatusParams = /*#__PURE__*/ zod.object({
  "essay_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the essay to look up'))
})

export const GetEssayReviewStatusResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('When a counselor completed it')),
  "essay_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Essay the review is for')),
  "requested_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('When the review was requested')),
  "status": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('open, completed, or refunded')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student who requested the review')),
  "transaction_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Ledger row this status came from'))
})


/**
 * Create a greeting for a person by name.
 */
export const createGreetingBodyNameMax = 30;



export const CreateGreetingBody = /*#__PURE__*/ zod.object({
  "name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.maxLength(createGreetingBodyNameMax)).check(/*#__PURE__*/ zod.describe('Name to greet'))
})

export const CreateGreetingResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "greeting": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Greeting message'))
})


/**
 * Spend a student's review balance to open a review on an essay.
 */
export const requestEssayReviewBodyAmountDefault = 1;



export const RequestEssayReviewBody = /*#__PURE__*/ zod.object({
  "amount": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(1)), requestEssayReviewBodyAmountDefault).check(/*#__PURE__*/ zod.describe('Number of review credits to spend. Positive; recorded on the ledger as a negative subtotal.')),
  "essay_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Essay to review')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student requesting the review'))
})

export const RequestEssayReviewResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "actor_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('User who caused the movement. Null until auth provides the caller.')),
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('When a counselor marked the review complete')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was created')),
  "entry_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Kind of movement: spend, refund, or adjustment')),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Essay under review. Null for an adjustment.')),
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Unique identifier for the transaction')),
  "refund": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('The negative row that reversed this charge, if it was refunded')),
  "status": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Lifecycle of a spend: open, completed, or refunded. Null for refund and adjustment rows.')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student whose balance moved')),
  "subtotal": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Signed change to the student\'s balance. Negative for a spend, positive for a refund or grant. Sums to the balance.')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was last updated'))
})


/**
 * Mark a review as having been completed by a counselor.
 */
export const CompleteEssayReviewParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the review to mark complete'))
})

export const CompleteEssayReviewResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "actor_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('User who caused the movement. Null until auth provides the caller.')),
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('When a counselor marked the review complete')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was created')),
  "entry_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Kind of movement: spend, refund, or adjustment')),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Essay under review. Null for an adjustment.')),
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Unique identifier for the transaction')),
  "refund": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('The negative row that reversed this charge, if it was refunded')),
  "status": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Lifecycle of a spend: open, completed, or refunded. Null for refund and adjustment rows.')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student whose balance moved')),
  "subtotal": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Signed change to the student\'s balance. Negative for a spend, positive for a refund or grant. Sums to the balance.')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was last updated'))
})


/**
 * Refund a review that has not been completed, crediting the balance back to the student.
 */
export const RefundEssayReviewParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the charge to refund'))
})

export const RefundEssayReviewResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "refund": /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "actor_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('User who caused the movement. Null until auth provides the caller.')),
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('When a counselor marked the review complete')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was created')),
  "entry_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Kind of movement: spend, refund, or adjustment')),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Essay under review. Null for an adjustment.')),
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Unique identifier for the transaction')),
  "refund": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('The negative row that reversed this charge, if it was refunded')),
  "status": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Lifecycle of a spend: open, completed, or refunded. Null for refund and adjustment rows.')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student whose balance moved')),
  "subtotal": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Signed change to the student\'s balance. Negative for a spend, positive for a refund or grant. Sums to the balance.')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was last updated'))
}).check(/*#__PURE__*/ zod.describe('The negative row that reversed the charge')),
  "transaction": /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "actor_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('User who caused the movement. Null until auth provides the caller.')),
  "completed_at": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.datetime({"offset":true})).check(/*#__PURE__*/ zod.describe('When a counselor marked the review complete')),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was created')),
  "entry_type": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Kind of movement: spend, refund, or adjustment')),
  "essay_id": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Essay under review. Null for an adjustment.')),
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Unique identifier for the transaction')),
  "refund": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('The negative row that reversed this charge, if it was refunded')),
  "status": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()).check(/*#__PURE__*/ zod.describe('Lifecycle of a spend: open, completed, or refunded. Null for refund and adjustment rows.')),
  "student_id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Student whose balance moved')),
  "subtotal": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.describe('Signed change to the student\'s balance. Negative for a spend, positive for a refund or grant. Sums to the balance.')),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}).check(/*#__PURE__*/ zod.describe('Timestamp when the transaction was last updated'))
}).check(/*#__PURE__*/ zod.describe('The original charge, now marked refunded'))
})


/**
 * Overwrite a student's review balance with an absolute value, recording the change in the review ledger.
 */
export const SetStudentReviewBalanceParams = /*#__PURE__*/ zod.object({
  "id": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('ID of the student'))
})

export const setStudentReviewBalanceBodyReviewBalanceMin = 0;



export const SetStudentReviewBalanceBody = /*#__PURE__*/ zod.object({
  "review_balance": /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(setStudentReviewBalanceBodyReviewBalanceMin)).check(/*#__PURE__*/ zod.describe('Absolute value to set the student\'s review balance to'))
})

export const SetStudentReviewBalanceResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "counselor_id": /*#__PURE__*/ zod.string(),
  "gpa": /*#__PURE__*/ zod.int(),
  "id": /*#__PURE__*/ zod.string(),
  "organization": /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  "review_balance": /*#__PURE__*/ zod.int(),
  "user_id": /*#__PURE__*/ zod.string(),
  "year": /*#__PURE__*/ zod.string()
})
