/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod/mini';

/**
 * Get a greeting for a person by name.
 */
export const getGreetingPathNameMax = 30;



export const GetGreetingParams = /*#__PURE__*/ zod.object({
  "name": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.maxLength(getGreetingPathNameMax)).check(/*#__PURE__*/ zod.describe('Name to greet'))
})

export const GetGreetingResponse = /*#__PURE__*/ zod.object({
  "$schema": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.url()).check(/*#__PURE__*/ zod.describe('A URL to the JSON Schema for this object.')),
  "message": /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.describe('Greeting message'))
})
