/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  PersonalCollegeApplication
} from '../../models';


export const getListPersonalCollegeApplicationsResponseMock = (): PersonalCollegeApplication[] | null => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), application_type: faker.string.alpha({length: {min: 10, max: 20}}), category: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', global_college_id: faker.number.int(), id: faker.number.int(), student_id: faker.string.alpha({length: {min: 10, max: 20}}), updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getCreatePersonalCollegeApplicationResponseMock = (overrideResponse: Partial<Extract<PersonalCollegeApplication, object>> = {}): PersonalCollegeApplication => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), application_type: faker.string.alpha({length: {min: 10, max: 20}}), category: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', global_college_id: faker.number.int(), id: faker.number.int(), student_id: faker.string.alpha({length: {min: 10, max: 20}}), updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

