/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  PersonalCollegeApplication
} from '../../models';

import {
  getCreatePersonalCollegeApplicationResponseMock,
  getListPersonalCollegeApplicationsResponseMock
} from './personal-college-applications.faker';

export { getListPersonalCollegeApplicationsResponseMock, getCreatePersonalCollegeApplicationResponseMock } from './personal-college-applications.faker';


export const getListPersonalCollegeApplicationsMockHandler = (overrideResponse?: PersonalCollegeApplication[] | null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PersonalCollegeApplication[] | null> | PersonalCollegeApplication[] | null), options?: RequestHandlerOptions) => {
  return http.get('*/applications', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListPersonalCollegeApplicationsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreatePersonalCollegeApplicationMockHandler = (overrideResponse?: PersonalCollegeApplication | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PersonalCollegeApplication> | PersonalCollegeApplication), options?: RequestHandlerOptions) => {
  return http.post('*/applications', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreatePersonalCollegeApplicationResponseMock(),
      { status: 200
      })
  }, options)
}
export const getPersonalCollegeApplicationsMock = () => [
  getListPersonalCollegeApplicationsMockHandler(),
  getCreatePersonalCollegeApplicationMockHandler()
]
