/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreatePersonalCollegeApplicationRequestBody,
  ErrorModel,
  PersonalCollegeApplication
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type listPersonalCollegeApplicationsResponse200 = {
  data: PersonalCollegeApplication[] | null
  status: 200
}

export type listPersonalCollegeApplicationsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listPersonalCollegeApplicationsResponseSuccess = (listPersonalCollegeApplicationsResponse200) & {
  headers: Headers;
};
export type listPersonalCollegeApplicationsResponseError = (listPersonalCollegeApplicationsResponseDefault) & {
  headers: Headers;
};

export type listPersonalCollegeApplicationsResponse = (listPersonalCollegeApplicationsResponseSuccess | listPersonalCollegeApplicationsResponseError)

export const getListPersonalCollegeApplicationsUrl = () => {




  return `http://127.0.0.1:8080/applications`
}

/**
 * List all college applications for the authenticated student.
 */
export const listPersonalCollegeApplications = async ( options?: RequestInit): Promise<listPersonalCollegeApplicationsResponse> => {

  const res = await fetch(getListPersonalCollegeApplicationsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listPersonalCollegeApplicationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listPersonalCollegeApplicationsResponse
}




export const getListPersonalCollegeApplicationsKey = () => [`http://127.0.0.1:8080/applications`] as const;

export type ListPersonalCollegeApplicationsQueryResult = NonNullable<Awaited<ReturnType<typeof listPersonalCollegeApplications>>>

export const useListPersonalCollegeApplications = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listPersonalCollegeApplications>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListPersonalCollegeApplicationsKey() : null);
  const swrFn = () => listPersonalCollegeApplications(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type createPersonalCollegeApplicationResponse200 = {
  data: PersonalCollegeApplication
  status: 200
}

export type createPersonalCollegeApplicationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createPersonalCollegeApplicationResponseSuccess = (createPersonalCollegeApplicationResponse200) & {
  headers: Headers;
};
export type createPersonalCollegeApplicationResponseError = (createPersonalCollegeApplicationResponseDefault) & {
  headers: Headers;
};

export type createPersonalCollegeApplicationResponse = (createPersonalCollegeApplicationResponseSuccess | createPersonalCollegeApplicationResponseError)

export const getCreatePersonalCollegeApplicationUrl = () => {




  return `http://127.0.0.1:8080/applications`
}

/**
 * Create a personal college application for the authenticated student.
 */
export const createPersonalCollegeApplication = async (createPersonalCollegeApplicationRequestBody: NonReadonly<CreatePersonalCollegeApplicationRequestBody>, options?: RequestInit): Promise<createPersonalCollegeApplicationResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreatePersonalCollegeApplicationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createPersonalCollegeApplicationRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createPersonalCollegeApplicationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createPersonalCollegeApplicationResponse
}




export const getCreatePersonalCollegeApplicationMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<CreatePersonalCollegeApplicationRequestBody> }) => {
    return createPersonalCollegeApplication(arg, options);
  }
}
export const getCreatePersonalCollegeApplicationMutationKey = () => [`http://127.0.0.1:8080/applications`] as const;

export type CreatePersonalCollegeApplicationMutationResult = NonNullable<Awaited<ReturnType<typeof createPersonalCollegeApplication>>>

export const useCreatePersonalCollegeApplication = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createPersonalCollegeApplication>>, TError, Key, NonReadonly<CreatePersonalCollegeApplicationRequestBody>, Awaited<ReturnType<typeof createPersonalCollegeApplication>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreatePersonalCollegeApplicationMutationKey();
  const swrFn = getCreatePersonalCollegeApplicationMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
