// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	dbinterface "inspirate-consulting/internal/data/db-interface"

	mock "github.com/stretchr/testify/mock"

	models "inspirate-consulting/internal/models"

	uuid "github.com/google/uuid"
)

// EssayReviewRepository is an autogenerated mock type for the EssayReviewRepository type
type EssayReviewRepository struct {
	mock.Mock
}

// AdjustStudentBalance provides a mock function with given fields: ctx, db, id, delta
func (_m *EssayReviewRepository) AdjustStudentBalance(ctx context.Context, db dbinterface.QueryInterface, id uuid.UUID, delta int) error {
	ret := _m.Called(ctx, db, id, delta)

	if len(ret) == 0 {
		panic("no return value specified for AdjustStudentBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID, int) error); ok {
		r0 = rf(ctx, db, id, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DB provides a mock function with no fields
func (_m *EssayReviewRepository) DB() dbinterface.QueryInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 dbinterface.QueryInterface
	if rf, ok := ret.Get(0).(func() dbinterface.QueryInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbinterface.QueryInterface)
		}
	}

	return r0
}

// FindEssayReviewStatus provides a mock function with given fields: ctx, db, essayID
func (_m *EssayReviewRepository) FindEssayReviewStatus(ctx context.Context, db dbinterface.QueryInterface, essayID uuid.UUID) (*models.EssayReviewStatus, error) {
	ret := _m.Called(ctx, db, essayID)

	if len(ret) == 0 {
		panic("no return value specified for FindEssayReviewStatus")
	}

	var r0 *models.EssayReviewStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) (*models.EssayReviewStatus, error)); ok {
		return rf(ctx, db, essayID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) *models.EssayReviewStatus); ok {
		r0 = rf(ctx, db, essayID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EssayReviewStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) error); ok {
		r1 = rf(ctx, db, essayID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOpenReviewForEssay provides a mock function with given fields: ctx, db, essayID
func (_m *EssayReviewRepository) FindOpenReviewForEssay(ctx context.Context, db dbinterface.QueryInterface, essayID uuid.UUID) (*uuid.UUID, error) {
	ret := _m.Called(ctx, db, essayID)

	if len(ret) == 0 {
		panic("no return value specified for FindOpenReviewForEssay")
	}

	var r0 *uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) (*uuid.UUID, error)); ok {
		return rf(ctx, db, essayID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) *uuid.UUID); ok {
		r0 = rf(ctx, db, essayID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) error); ok {
		r1 = rf(ctx, db, essayID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertAdjustment provides a mock function with given fields: ctx, db, studentID, delta
func (_m *EssayReviewRepository) InsertAdjustment(ctx context.Context, db dbinterface.QueryInterface, studentID uuid.UUID, delta int) error {
	ret := _m.Called(ctx, db, studentID, delta)

	if len(ret) == 0 {
		panic("no return value specified for InsertAdjustment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID, int) error); ok {
		r0 = rf(ctx, db, studentID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertRefund provides a mock function with given fields: ctx, db, charge
func (_m *EssayReviewRepository) InsertRefund(ctx context.Context, db dbinterface.QueryInterface, charge *models.EssayReviewTransaction) (*models.EssayReviewTransaction, error) {
	ret := _m.Called(ctx, db, charge)

	if len(ret) == 0 {
		panic("no return value specified for InsertRefund")
	}

	var r0 *models.EssayReviewTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, *models.EssayReviewTransaction) (*models.EssayReviewTransaction, error)); ok {
		return rf(ctx, db, charge)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, *models.EssayReviewTransaction) *models.EssayReviewTransaction); ok {
		r0 = rf(ctx, db, charge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EssayReviewTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dbinterface.QueryInterface, *models.EssayReviewTransaction) error); ok {
		r1 = rf(ctx, db, charge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertSpend provides a mock function with given fields: ctx, db, studentID, essayID, amount
func (_m *EssayReviewRepository) InsertSpend(ctx context.Context, db dbinterface.QueryInterface, studentID uuid.UUID, essayID uuid.UUID, amount int) (*models.EssayReviewTransaction, error) {
	ret := _m.Called(ctx, db, studentID, essayID, amount)

	if len(ret) == 0 {
		panic("no return value specified for InsertSpend")
	}

	var r0 *models.EssayReviewTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID, uuid.UUID, int) (*models.EssayReviewTransaction, error)); ok {
		return rf(ctx, db, studentID, essayID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID, uuid.UUID, int) *models.EssayReviewTransaction); ok {
		r0 = rf(ctx, db, studentID, essayID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EssayReviewTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dbinterface.QueryInterface, uuid.UUID, uuid.UUID, int) error); ok {
		r1 = rf(ctx, db, studentID, essayID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRefund provides a mock function with given fields: ctx, db, chargeID, reversalID
func (_m *EssayReviewRepository) LinkRefund(ctx context.Context, db dbinterface.QueryInterface, chargeID uuid.UUID, reversalID uuid.UUID) (*models.EssayReviewTransaction, error) {
	ret := _m.Called(ctx, db, chargeID, reversalID)

	if len(ret) == 0 {
		panic("no return value specified for LinkRefund")
	}

	var r0 *models.EssayReviewTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID, uuid.UUID) (*models.EssayReviewTransaction, error)); ok {
		return rf(ctx, db, chargeID, reversalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID, uuid.UUID) *models.EssayReviewTransaction); ok {
		r0 = rf(ctx, db, chargeID, reversalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EssayReviewTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dbinterface.QueryInterface, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, db, chargeID, reversalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockStudent provides a mock function with given fields: ctx, db, id
func (_m *EssayReviewRepository) LockStudent(ctx context.Context, db dbinterface.QueryInterface, id uuid.UUID) (*models.Student, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for LockStudent")
	}

	var r0 *models.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) (*models.Student, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) *models.Student); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockTransaction provides a mock function with given fields: ctx, db, id
func (_m *EssayReviewRepository) LockTransaction(ctx context.Context, db dbinterface.QueryInterface, id uuid.UUID) (*models.EssayReviewTransaction, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for LockTransaction")
	}

	var r0 *models.EssayReviewTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) (*models.EssayReviewTransaction, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) *models.EssayReviewTransaction); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EssayReviewTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkCompleted provides a mock function with given fields: ctx, db, id
func (_m *EssayReviewRepository) MarkCompleted(ctx context.Context, db dbinterface.QueryInterface, id uuid.UUID) (*models.EssayReviewTransaction, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkCompleted")
	}

	var r0 *models.EssayReviewTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) (*models.EssayReviewTransaction, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) *models.EssayReviewTransaction); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EssayReviewTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dbinterface.QueryInterface, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetStudentBalance provides a mock function with given fields: ctx, db, id, reviewBalance
func (_m *EssayReviewRepository) SetStudentBalance(ctx context.Context, db dbinterface.QueryInterface, id uuid.UUID, reviewBalance int) error {
	ret := _m.Called(ctx, db, id, reviewBalance)

	if len(ret) == 0 {
		panic("no return value specified for SetStudentBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dbinterface.QueryInterface, uuid.UUID, int) error); ok {
		r0 = rf(ctx, db, id, reviewBalance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *EssayReviewRepository) WithTx(ctx context.Context, fn func(dbinterface.QueryInterface) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(dbinterface.QueryInterface) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEssayReviewRepository creates a new instance of EssayReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEssayReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EssayReviewRepository {
	mock := &EssayReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
