// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "inspirate-consulting/internal/models"

	uuid "github.com/google/uuid"
)

// EssayRepository is an autogenerated mock type for the EssayRepository type
type EssayRepository struct {
	mock.Mock
}

// CreateEssay provides a mock function with given fields: ctx, essay
func (_m *EssayRepository) CreateEssay(ctx context.Context, essay models.Essays) error {
	ret := _m.Called(ctx, essay)

	if len(ret) == 0 {
		panic("no return value specified for CreateEssay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Essays) error); ok {
		r0 = rf(ctx, essay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEssaysFromStudent provides a mock function with given fields: ctx, studentID
func (_m *EssayRepository) GetEssaysFromStudent(ctx context.Context, studentID uuid.UUID) ([]models.Essays, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetEssaysFromStudent")
	}

	var r0 []models.Essays
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Essays, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Essays); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Essays)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, essayID, status
func (_m *EssayRepository) UpdateStatus(ctx context.Context, essayID uuid.UUID, status models.Status) error {
	ret := _m.Called(ctx, essayID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.Status) error); ok {
		r0 = rf(ctx, essayID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEssayRepository creates a new instance of EssayRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEssayRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EssayRepository {
	mock := &EssayRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
