// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "inspirate-consulting/internal/models"

	uuid "github.com/google/uuid"
)

// EssayGroupRepository is an autogenerated mock type for the EssayGroupRepository type
type EssayGroupRepository struct {
	mock.Mock
}

// CreateEssayGroup provides a mock function with given fields: ctx, group
func (_m *EssayGroupRepository) CreateEssayGroup(ctx context.Context, group models.CreateEssayGroupBody) (*models.EssayGroups, error) {
	ret := _m.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for CreateEssayGroup")
	}

	var r0 *models.EssayGroups
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateEssayGroupBody) (*models.EssayGroups, error)); ok {
		return rf(ctx, group)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateEssayGroupBody) *models.EssayGroups); ok {
		r0 = rf(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EssayGroups)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateEssayGroupBody) error); ok {
		r1 = rf(ctx, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEssayGroups provides a mock function with given fields: ctx, studentID
func (_m *EssayGroupRepository) ListEssayGroups(ctx context.Context, studentID uuid.UUID) ([]models.EssayGroups, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for ListEssayGroups")
	}

	var r0 []models.EssayGroups
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.EssayGroups, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.EssayGroups); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EssayGroups)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEssayGroupRepository creates a new instance of EssayGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEssayGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EssayGroupRepository {
	mock := &EssayGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
