// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "inspirate-consulting/internal/models"
)

// GlobalCollegeRepository is an autogenerated mock type for the GlobalCollegeRepository type
type GlobalCollegeRepository struct {
	mock.Mock
}

// CreateGlobalCollege provides a mock function with given fields: ctx, global_college
func (_m *GlobalCollegeRepository) CreateGlobalCollege(ctx context.Context, global_college models.CreateGlobalCollegeRequestBody) (*models.GlobalCollege, error) {
	ret := _m.Called(ctx, global_college)

	if len(ret) == 0 {
		panic("no return value specified for CreateGlobalCollege")
	}

	var r0 *models.GlobalCollege
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateGlobalCollegeRequestBody) (*models.GlobalCollege, error)); ok {
		return rf(ctx, global_college)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateGlobalCollegeRequestBody) *models.GlobalCollege); ok {
		r0 = rf(ctx, global_college)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GlobalCollege)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateGlobalCollegeRequestBody) error); ok {
		r1 = rf(ctx, global_college)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGlobalCollege provides a mock function with given fields: ctx, id
func (_m *GlobalCollegeRepository) GetGlobalCollege(ctx context.Context, id int64) (*models.GlobalCollege, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalCollege")
	}

	var r0 *models.GlobalCollege
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.GlobalCollege, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.GlobalCollege); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GlobalCollege)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListGlobalColleges provides a mock function with given fields: ctx
func (_m *GlobalCollegeRepository) ListGlobalColleges(ctx context.Context) ([]models.GlobalCollege, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListGlobalColleges")
	}

	var r0 []models.GlobalCollege
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.GlobalCollege, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.GlobalCollege); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GlobalCollege)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGlobalCollegeRepository creates a new instance of GlobalCollegeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGlobalCollegeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GlobalCollegeRepository {
	mock := &GlobalCollegeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
