// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "inspirate-consulting/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MediaRepository is an autogenerated mock type for the MediaRepository type
type MediaRepository struct {
	mock.Mock
}

// CreateMedia provides a mock function with given fields: ctx, item
func (_m *MediaRepository) CreateMedia(ctx context.Context, item *models.CreateMediaRequestBody) (*models.Media, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateMedia")
	}

	var r0 *models.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateMediaRequestBody) (*models.Media, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateMediaRequestBody) *models.Media); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateMediaRequestBody) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMedia provides a mock function with given fields: ctx, id
func (_m *MediaRepository) DeleteMedia(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMedia provides a mock function with given fields: ctx, id
func (_m *MediaRepository) GetMedia(ctx context.Context, id string) (*models.Media, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMedia")
	}

	var r0 *models.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Media, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Media); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllMedia provides a mock function with given fields: ctx
func (_m *MediaRepository) ListAllMedia(ctx context.Context) ([]models.Media, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllMedia")
	}

	var r0 []models.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Media, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Media); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMediaRepository creates a new instance of MediaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaRepository {
	mock := &MediaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
