// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "inspirate-consulting/internal/models"
)

// MediaAccessRepository is an autogenerated mock type for the MediaAccessRepository type
type MediaAccessRepository struct {
	mock.Mock
}

// GrantMediaAccess provides a mock function with given fields: ctx, body
func (_m *MediaAccessRepository) GrantMediaAccess(ctx context.Context, body *models.GrantMediaAccessRequestBody) (*models.MediaAccess, error) {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for GrantMediaAccess")
	}

	var r0 *models.MediaAccess
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GrantMediaAccessRequestBody) (*models.MediaAccess, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.GrantMediaAccessRequestBody) *models.MediaAccess); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MediaAccess)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.GrantMediaAccessRequestBody) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAccessibleMedia provides a mock function with given fields: ctx, studentID, limit, offset
func (_m *MediaAccessRepository) ListAccessibleMedia(ctx context.Context, studentID string, limit int, offset int) ([]models.Media, error) {
	ret := _m.Called(ctx, studentID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAccessibleMedia")
	}

	var r0 []models.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Media, error)); ok {
		return rf(ctx, studentID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Media); ok {
		r0 = rf(ctx, studentID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, studentID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeMediaAccess provides a mock function with given fields: ctx, id
func (_m *MediaAccessRepository) RevokeMediaAccess(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeMediaAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMediaAccessRepository creates a new instance of MediaAccessRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaAccessRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaAccessRepository {
	mock := &MediaAccessRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
