// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "inspirate-consulting/internal/models"

	uuid "github.com/google/uuid"
)

// NotificationPreferencesRepository is an autogenerated mock type for the NotificationPreferencesRepository type
type NotificationPreferencesRepository struct {
	mock.Mock
}

// GetNotificationPreferences provides a mock function with given fields: ctx, userID
func (_m *NotificationPreferencesRepository) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (*models.NotificationPreferences, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationPreferences")
	}

	var r0 *models.NotificationPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.NotificationPreferences, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.NotificationPreferences); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.NotificationPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNotificationPreferences provides a mock function with given fields: ctx, userID, preferences
func (_m *NotificationPreferencesRepository) UpdateNotificationPreferences(ctx context.Context, userID uuid.UUID, preferences models.UpdateNotificationPreferencesRequestBody) (*models.NotificationPreferences, error) {
	ret := _m.Called(ctx, userID, preferences)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationPreferences")
	}

	var r0 *models.NotificationPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.UpdateNotificationPreferencesRequestBody) (*models.NotificationPreferences, error)); ok {
		return rf(ctx, userID, preferences)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.UpdateNotificationPreferencesRequestBody) *models.NotificationPreferences); ok {
		r0 = rf(ctx, userID, preferences)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.NotificationPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.UpdateNotificationPreferencesRequestBody) error); ok {
		r1 = rf(ctx, userID, preferences)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNotificationPreferencesRepository creates a new instance of NotificationPreferencesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationPreferencesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationPreferencesRepository {
	mock := &NotificationPreferencesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
