// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "inspirate-consulting/internal/models"
)

// PersonalCollegeApplicationRepository is an autogenerated mock type for the PersonalCollegeApplicationRepository type
type PersonalCollegeApplicationRepository struct {
	mock.Mock
}

// CreatePersonalCollegeApplication provides a mock function with given fields: ctx, studentID, application
func (_m *PersonalCollegeApplicationRepository) CreatePersonalCollegeApplication(ctx context.Context, studentID string, application models.CreatePersonalCollegeApplicationRequestBody) (*models.PersonalCollegeApplication, error) {
	ret := _m.Called(ctx, studentID, application)

	if len(ret) == 0 {
		panic("no return value specified for CreatePersonalCollegeApplication")
	}

	var r0 *models.PersonalCollegeApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.CreatePersonalCollegeApplicationRequestBody) (*models.PersonalCollegeApplication, error)); ok {
		return rf(ctx, studentID, application)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.CreatePersonalCollegeApplicationRequestBody) *models.PersonalCollegeApplication); ok {
		r0 = rf(ctx, studentID, application)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PersonalCollegeApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.CreatePersonalCollegeApplicationRequestBody) error); ok {
		r1 = rf(ctx, studentID, application)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPersonalCollegeApplicationsByStudentID provides a mock function with given fields: ctx, studentID
func (_m *PersonalCollegeApplicationRepository) ListPersonalCollegeApplicationsByStudentID(ctx context.Context, studentID string) ([]models.PersonalCollegeApplication, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for ListPersonalCollegeApplicationsByStudentID")
	}

	var r0 []models.PersonalCollegeApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.PersonalCollegeApplication, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.PersonalCollegeApplication); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PersonalCollegeApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPersonalCollegeApplicationRepository creates a new instance of PersonalCollegeApplicationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonalCollegeApplicationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonalCollegeApplicationRepository {
	mock := &PersonalCollegeApplicationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
