// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "inspirate-consulting/internal/models"
)

// PersonalCollegeApplicationRepository is an autogenerated mock type for the PersonalCollegeApplicationRepository type
type PersonalCollegeApplicationRepository struct {
	mock.Mock
}

// CreatePersonalCollegeApplication provides a mock function with given fields: ctx, studentID, application
func (_m *PersonalCollegeApplicationRepository) CreatePersonalCollegeApplication(ctx context.Context, studentID string, application models.CreatePersonalCollegeApplicationRequestBody) (*models.PersonalCollegeApplication, error) {
	ret := _m.Called(ctx, studentID, application)

	if len(ret) == 0 {
		panic("no return value specified for CreatePersonalCollegeApplication")
	}

	var r0 *models.PersonalCollegeApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.CreatePersonalCollegeApplicationRequestBody) (*models.PersonalCollegeApplication, error)); ok {
		return rf(ctx, studentID, application)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.CreatePersonalCollegeApplicationRequestBody) *models.PersonalCollegeApplication); ok {
		r0 = rf(ctx, studentID, application)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PersonalCollegeApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.CreatePersonalCollegeApplicationRequestBody) error); ok {
		r1 = rf(ctx, studentID, application)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePersonalCollegeApplication provides a mock function with given fields: ctx, studentID, applicationID
func (_m *PersonalCollegeApplicationRepository) DeletePersonalCollegeApplication(ctx context.Context, studentID string, applicationID int64) error {
	ret := _m.Called(ctx, studentID, applicationID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePersonalCollegeApplication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, studentID, applicationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListPersonalCollegeApplicationsByStudentID provides a mock function with given fields: ctx, studentID
func (_m *PersonalCollegeApplicationRepository) ListPersonalCollegeApplicationsByStudentID(ctx context.Context, studentID string) ([]models.PersonalCollegeApplication, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for ListPersonalCollegeApplicationsByStudentID")
	}

	var r0 []models.PersonalCollegeApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.PersonalCollegeApplication, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.PersonalCollegeApplication); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PersonalCollegeApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateApplicationRank provides a mock function with given fields: ctx, studentID, applicationID, newRank
func (_m *PersonalCollegeApplicationRepository) UpdateApplicationRank(ctx context.Context, studentID string, applicationID int64, newRank *int) ([]models.PersonalCollegeApplication, error) {
	ret := _m.Called(ctx, studentID, applicationID, newRank)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApplicationRank")
	}

	var r0 []models.PersonalCollegeApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, *int) ([]models.PersonalCollegeApplication, error)); ok {
		return rf(ctx, studentID, applicationID, newRank)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, *int) []models.PersonalCollegeApplication); ok {
		r0 = rf(ctx, studentID, applicationID, newRank)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PersonalCollegeApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, *int) error); ok {
		r1 = rf(ctx, studentID, applicationID, newRank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePersonalCollegeApplication provides a mock function with given fields: ctx, studentID, applicationID, input
func (_m *PersonalCollegeApplicationRepository) UpdatePersonalCollegeApplication(ctx context.Context, studentID string, applicationID int64, input models.UpdatePersonalCollegeApplicationRequestBody) (*models.PersonalCollegeApplication, error) {
	ret := _m.Called(ctx, studentID, applicationID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePersonalCollegeApplication")
	}

	var r0 *models.PersonalCollegeApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, models.UpdatePersonalCollegeApplicationRequestBody) (*models.PersonalCollegeApplication, error)); ok {
		return rf(ctx, studentID, applicationID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, models.UpdatePersonalCollegeApplicationRequestBody) *models.PersonalCollegeApplication); ok {
		r0 = rf(ctx, studentID, applicationID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PersonalCollegeApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, models.UpdatePersonalCollegeApplicationRequestBody) error); ok {
		r1 = rf(ctx, studentID, applicationID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPersonalCollegeApplicationRepository creates a new instance of PersonalCollegeApplicationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonalCollegeApplicationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonalCollegeApplicationRepository {
	mock := &PersonalCollegeApplicationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
