// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "inspirate-consulting/internal/models"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TodoItemRepository is an autogenerated mock type for the TodoItemRepository type
type TodoItemRepository struct {
	mock.Mock
}

// CreateTodoItem provides a mock function with given fields: ctx, item
func (_m *TodoItemRepository) CreateTodoItem(ctx context.Context, item *models.TodoItem) (*models.TodoItem, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodoItem")
	}

	var r0 *models.TodoItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TodoItem) (*models.TodoItem, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.TodoItem) *models.TodoItem); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TodoItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.TodoItem) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTodoItemsByStudent provides a mock function with given fields: ctx, studentID
func (_m *TodoItemRepository) GetTodoItemsByStudent(ctx context.Context, studentID string) ([]models.TodoItem, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetTodoItemsByStudent")
	}

	var r0 []models.TodoItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.TodoItem, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.TodoItem); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TodoItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTodoItemCompletedAt provides a mock function with given fields: ctx, id, completedAt
func (_m *TodoItemRepository) UpdateTodoItemCompletedAt(ctx context.Context, id string, completedAt *time.Time) (*models.TodoItem, error) {
	ret := _m.Called(ctx, id, completedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodoItemCompletedAt")
	}

	var r0 *models.TodoItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time) (*models.TodoItem, error)); ok {
		return rf(ctx, id, completedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time) *models.TodoItem); ok {
		r0 = rf(ctx, id, completedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TodoItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *time.Time) error); ok {
		r1 = rf(ctx, id, completedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTodoItemRepository creates a new instance of TodoItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoItemRepository {
	mock := &TodoItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
