// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "inspirate-consulting/internal/models"
)

// VideoRepository is an autogenerated mock type for the VideoRepository type
type VideoRepository struct {
	mock.Mock
}

// GetVideo provides a mock function with given fields: ctx, s3Key
func (_m *VideoRepository) GetVideo(ctx context.Context, s3Key string) (*models.Video, error) {
	ret := _m.Called(ctx, s3Key)

	if len(ret) == 0 {
		panic("no return value specified for GetVideo")
	}

	var r0 *models.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Video, error)); ok {
		return rf(ctx, s3Key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Video); ok {
		r0 = rf(ctx, s3Key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, s3Key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListVideos provides a mock function with given fields: ctx
func (_m *VideoRepository) ListVideos(ctx context.Context) ([]models.Video, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListVideos")
	}

	var r0 []models.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Video, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Video); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PresignUpload provides a mock function with given fields: ctx, originalFilename
func (_m *VideoRepository) PresignUpload(ctx context.Context, originalFilename string) (*models.PresignUploadResponse, error) {
	ret := _m.Called(ctx, originalFilename)

	if len(ret) == 0 {
		panic("no return value specified for PresignUpload")
	}

	var r0 *models.PresignUploadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PresignUploadResponse, error)); ok {
		return rf(ctx, originalFilename)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PresignUploadResponse); ok {
		r0 = rf(ctx, originalFilename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PresignUploadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, originalFilename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVideoRepository creates a new instance of VideoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVideoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VideoRepository {
	mock := &VideoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
