/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  LoginResponse
} from '../../models';


export const getLoginUserResponseMock = (overrideResponse: Partial<Extract<LoginResponse, object>> = {}): LoginResponse => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), access_token: faker.string.alpha({length: {min: 10, max: 20}}), error: {}, expires_in: faker.number.int(), refresh_token: faker.string.alpha({length: {min: 10, max: 20}}), reset_time: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', null]), token_type: faker.string.alpha({length: {min: 10, max: 20}}), user: {id: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

