/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  Media
} from '../../models';


export const getListMediaResponseMock = (): Media[] | null => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), description: faker.string.alpha({length: {min: 10, max: 20}}), id: faker.string.alpha({length: {min: 10, max: 20}}), length_in_mins: faker.number.int(), s3_key: faker.string.alpha({length: {min: 10, max: 20}}), school_year: faker.helpers.arrayElement([faker.number.int(), null]), title: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getCreateMediaResponseMock = (overrideResponse: Partial<Extract<Media, object>> = {}): Media => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), description: faker.string.alpha({length: {min: 10, max: 20}}), id: faker.string.alpha({length: {min: 10, max: 20}}), length_in_mins: faker.number.int(), s3_key: faker.string.alpha({length: {min: 10, max: 20}}), school_year: faker.helpers.arrayElement([faker.number.int(), null]), title: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getGetMediaResponseMock = (overrideResponse: Partial<Extract<Media, object>> = {}): Media => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), description: faker.string.alpha({length: {min: 10, max: 20}}), id: faker.string.alpha({length: {min: 10, max: 20}}), length_in_mins: faker.number.int(), s3_key: faker.string.alpha({length: {min: 10, max: 20}}), school_year: faker.helpers.arrayElement([faker.number.int(), null]), title: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

