/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Media
} from '../../models';

import {
  getCreateMediaResponseMock,
  getGetMediaResponseMock,
  getListMediaResponseMock
} from './media.faker';

export { getListMediaResponseMock, getCreateMediaResponseMock, getGetMediaResponseMock } from './media.faker';


export const getListMediaMockHandler = (overrideResponse?: Media[] | null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Media[] | null> | Media[] | null), options?: RequestHandlerOptions) => {
  return http.get('*/media', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListMediaResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateMediaMockHandler = (overrideResponse?: Media | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Media> | Media), options?: RequestHandlerOptions) => {
  return http.post('*/media', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateMediaResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteMediaMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/media/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getGetMediaMockHandler = (overrideResponse?: Media | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Media> | Media), options?: RequestHandlerOptions) => {
  return http.get('*/media/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMediaResponseMock(),
      { status: 200
      })
  }, options)
}
export const getMediaMock = () => [
  getListMediaMockHandler(),
  getCreateMediaMockHandler(),
  getDeleteMediaMockHandler(),
  getGetMediaMockHandler()
]
