/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreateMediaRequestBody,
  ErrorModel,
  Media
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type listMediaResponse200 = {
  data: Media[] | null
  status: 200
}

export type listMediaResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listMediaResponseSuccess = (listMediaResponse200) & {
  headers: Headers;
};
export type listMediaResponseError = (listMediaResponseDefault) & {
  headers: Headers;
};

export type listMediaResponse = (listMediaResponseSuccess | listMediaResponseError)

export const getListMediaUrl = () => {




  return `http://127.0.0.1:8080/media`
}

/**
 * Fetch all videos, through counselor view
 */
export const listMedia = async ( options?: RequestInit): Promise<listMediaResponse> => {

  const res = await fetch(getListMediaUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listMediaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listMediaResponse
}




export const getListMediaKey = () => [`http://127.0.0.1:8080/media`] as const;

export type ListMediaQueryResult = NonNullable<Awaited<ReturnType<typeof listMedia>>>

export const useListMedia = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listMedia>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListMediaKey() : null);
  const swrFn = () => listMedia(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type createMediaResponse200 = {
  data: Media
  status: 200
}

export type createMediaResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createMediaResponseSuccess = (createMediaResponse200) & {
  headers: Headers;
};
export type createMediaResponseError = (createMediaResponseDefault) & {
  headers: Headers;
};

export type createMediaResponse = (createMediaResponseSuccess | createMediaResponseError)

export const getCreateMediaUrl = () => {




  return `http://127.0.0.1:8080/media`
}

/**
 * Create a media/video
 */
export const createMedia = async (createMediaRequestBody: NonReadonly<CreateMediaRequestBody>, options?: RequestInit): Promise<createMediaResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateMediaUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createMediaRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createMediaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createMediaResponse
}




export const getCreateMediaMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<CreateMediaRequestBody> }) => {
    return createMedia(arg, options);
  }
}
export const getCreateMediaMutationKey = () => [`http://127.0.0.1:8080/media`] as const;

export type CreateMediaMutationResult = NonNullable<Awaited<ReturnType<typeof createMedia>>>

export const useCreateMedia = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createMedia>>, TError, Key, NonReadonly<CreateMediaRequestBody>, Awaited<ReturnType<typeof createMedia>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateMediaMutationKey();
  const swrFn = getCreateMediaMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type deleteMediaResponse204 = {
  data: void
  status: 204
}

export type deleteMediaResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type deleteMediaResponseSuccess = (deleteMediaResponse204) & {
  headers: Headers;
};
export type deleteMediaResponseError = (deleteMediaResponseDefault) & {
  headers: Headers;
};

export type deleteMediaResponse = (deleteMediaResponseSuccess | deleteMediaResponseError)

export const getDeleteMediaUrl = (id: string,) => {




  return `http://127.0.0.1:8080/media/${id}`
}

/**
 * Delete a video, through counselor view
 */
export const deleteMedia = async (id: string, options?: RequestInit): Promise<deleteMediaResponse> => {

  const res = await fetch(getDeleteMediaUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteMediaResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteMediaResponse
}




export const getDeleteMediaMutationFetcher = (id: string, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteMedia(id, options);
  }
}
export const getDeleteMediaMutationKey = (id: string,) => [`http://127.0.0.1:8080/media/${id}`] as const;

export type DeleteMediaMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMedia>>>

export const useDeleteMedia = <TError = Promise<ErrorModel>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteMedia>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteMedia>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteMediaMutationKey(id);
  const swrFn = getDeleteMediaMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMediaResponse200 = {
  data: Media
  status: 200
}

export type getMediaResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getMediaResponseSuccess = (getMediaResponse200) & {
  headers: Headers;
};
export type getMediaResponseError = (getMediaResponseDefault) & {
  headers: Headers;
};

export type getMediaResponse = (getMediaResponseSuccess | getMediaResponseError)

export const getGetMediaUrl = (id: string,) => {




  return `http://127.0.0.1:8080/media/${id}`
}

/**
 * Get a media/video
 */
export const getMedia = async (id: string, options?: RequestInit): Promise<getMediaResponse> => {

  const res = await fetch(getGetMediaUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMediaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMediaResponse
}




export const getGetMediaKey = (id: string,) => [`http://127.0.0.1:8080/media/${id}`] as const;

export type GetMediaQueryResult = NonNullable<Awaited<ReturnType<typeof getMedia>>>

export const useGetMedia = <TError = Promise<ErrorModel>>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMedia>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMediaKey(id) : null);
  const swrFn = () => getMedia(id, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
