/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreateTodoItemRequestBody,
  ErrorModel,
  TodoItem,
  UpdateTodoItemCompletedAtInputBody
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type getTodoItemsResponse200 = {
  data: TodoItem[] | null
  status: 200
}

export type getTodoItemsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getTodoItemsResponseSuccess = (getTodoItemsResponse200) & {
  headers: Headers;
};
export type getTodoItemsResponseError = (getTodoItemsResponseDefault) & {
  headers: Headers;
};

export type getTodoItemsResponse = (getTodoItemsResponseSuccess | getTodoItemsResponseError)

export const getGetTodoItemsUrl = () => {




  return `http://127.0.0.1:8080/todo-items`
}

/**
 * Get a student's to-do items
 */
export const getTodoItems = async ( options?: RequestInit): Promise<getTodoItemsResponse> => {

  const res = await fetch(getGetTodoItemsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getTodoItemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTodoItemsResponse
}




export const getGetTodoItemsKey = () => [`http://127.0.0.1:8080/todo-items`] as const;

export type GetTodoItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getTodoItems>>>

export const useGetTodoItems = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTodoItems>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTodoItemsKey() : null);
  const swrFn = () => getTodoItems(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type createTodoItemResponse200 = {
  data: TodoItem
  status: 200
}

export type createTodoItemResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createTodoItemResponseSuccess = (createTodoItemResponse200) & {
  headers: Headers;
};
export type createTodoItemResponseError = (createTodoItemResponseDefault) & {
  headers: Headers;
};

export type createTodoItemResponse = (createTodoItemResponseSuccess | createTodoItemResponseError)

export const getCreateTodoItemUrl = () => {




  return `http://127.0.0.1:8080/todo-items`
}

/**
 * Create a to-do item with a description and optional deadline
 */
export const createTodoItem = async (createTodoItemRequestBody: NonReadonly<CreateTodoItemRequestBody>, options?: RequestInit): Promise<createTodoItemResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateTodoItemUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTodoItemRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createTodoItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTodoItemResponse
}




export const getCreateTodoItemMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<CreateTodoItemRequestBody> }) => {
    return createTodoItem(arg, options);
  }
}
export const getCreateTodoItemMutationKey = () => [`http://127.0.0.1:8080/todo-items`] as const;

export type CreateTodoItemMutationResult = NonNullable<Awaited<ReturnType<typeof createTodoItem>>>

export const useCreateTodoItem = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createTodoItem>>, TError, Key, NonReadonly<CreateTodoItemRequestBody>, Awaited<ReturnType<typeof createTodoItem>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateTodoItemMutationKey();
  const swrFn = getCreateTodoItemMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type updateTodoItemCompletedResponse200 = {
  data: TodoItem
  status: 200
}

export type updateTodoItemCompletedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateTodoItemCompletedResponseSuccess = (updateTodoItemCompletedResponse200) & {
  headers: Headers;
};
export type updateTodoItemCompletedResponseError = (updateTodoItemCompletedResponseDefault) & {
  headers: Headers;
};

export type updateTodoItemCompletedResponse = (updateTodoItemCompletedResponseSuccess | updateTodoItemCompletedResponseError)

export const getUpdateTodoItemCompletedUrl = (id: string,) => {




  return `http://127.0.0.1:8080/todo-items/${id}`
}

/**
 * Update a to-do item's completion status
 */
export const updateTodoItemCompleted = async (id: string,
    updateTodoItemCompletedAtInputBody: NonReadonly<UpdateTodoItemCompletedAtInputBody>, options?: RequestInit): Promise<updateTodoItemCompletedResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getUpdateTodoItemCompletedUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateTodoItemCompletedAtInputBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateTodoItemCompletedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateTodoItemCompletedResponse
}




export const getUpdateTodoItemCompletedMutationFetcher = (id: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<UpdateTodoItemCompletedAtInputBody> }) => {
    return updateTodoItemCompleted(id, arg, options);
  }
}
export const getUpdateTodoItemCompletedMutationKey = (id: string,) => [`http://127.0.0.1:8080/todo-items/${id}`] as const;

export type UpdateTodoItemCompletedMutationResult = NonNullable<Awaited<ReturnType<typeof updateTodoItemCompleted>>>

export const useUpdateTodoItemCompleted = <TError = Promise<ErrorModel>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateTodoItemCompleted>>, TError, Key, NonReadonly<UpdateTodoItemCompletedAtInputBody>, Awaited<ReturnType<typeof updateTodoItemCompleted>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateTodoItemCompletedMutationKey(id);
  const swrFn = getUpdateTodoItemCompletedMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
