/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  TodoItem
} from '../../models';

import {
  getCreateTodoItemResponseMock,
  getGetTodoItemsResponseMock,
  getUpdateTodoItemCompletedResponseMock
} from './todo-items.faker';

export { getGetTodoItemsResponseMock, getCreateTodoItemResponseMock, getUpdateTodoItemCompletedResponseMock } from './todo-items.faker';


export const getGetTodoItemsMockHandler = (overrideResponse?: TodoItem[] | null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TodoItem[] | null> | TodoItem[] | null), options?: RequestHandlerOptions) => {
  return http.get('*/todo-items', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetTodoItemsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateTodoItemMockHandler = (overrideResponse?: TodoItem | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TodoItem> | TodoItem), options?: RequestHandlerOptions) => {
  return http.post('*/todo-items', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateTodoItemResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateTodoItemCompletedMockHandler = (overrideResponse?: TodoItem | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<TodoItem> | TodoItem), options?: RequestHandlerOptions) => {
  return http.patch('*/todo-items/:id', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateTodoItemCompletedResponseMock(),
      { status: 200
      })
  }, options)
}
export const getTodoItemsMock = () => [
  getGetTodoItemsMockHandler(),
  getCreateTodoItemMockHandler(),
  getUpdateTodoItemCompletedMockHandler()
]
