/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateUserBody,
  User
} from '../../models';

import {
  getCreateUserResponseMock,
  getFetchUserBySupabaseIdResponseMock,
  getFetchUserResponseMock
} from './user.faker';

export { getCreateUserResponseMock, getFetchUserBySupabaseIdResponseMock, getFetchUserResponseMock } from './user.faker';


export const getCreateUserMockHandler = (overrideResponse?: CreateUserBody | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateUserBody> | CreateUserBody), options?: RequestHandlerOptions) => {
  return http.post('*/user', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateUserResponseMock(),
      { status: 200
      })
  }, options)
}

export const getFetchUserBySupabaseIdMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.get('*/user/supabase/:supabaseId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getFetchUserBySupabaseIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getFetchUserMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.get('*/user/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getFetchUserResponseMock(),
      { status: 200
      })
  }, options)
}
export const getUserMock = () => [
  getCreateUserMockHandler(),
  getFetchUserBySupabaseIdMockHandler(),
  getFetchUserMockHandler()
]
