/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type { ChatMessage } from './chatMessage';

export interface ChatMessagePage {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
     * Newest first
     * @nullable
     */
  messages: ChatMessage[] | null;
  /**
     * Pass as cursor to get older messages; null when there are none
     * @nullable
     */
  next_cursor: string | null;
}
