/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface ChatSummary {
  last_message: string;
  last_message_at: string;
  last_message_id: string;
  /** @nullable */
  last_message_read_at: string | null;
  last_sender_id: string;
  other_user_id: string;
  other_user_name: string;
  /** @nullable */
  other_user_pfp_key: string | null;
  /** Messages from the other user the current user has not read */
  unread_count: number;
}
