/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface ChatMessage {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  /**
     * Null if the message was never edited
     * @nullable
     */
  edited_at: string | null;
  id: string;
  message: string;
  /**
     * Null if the recipient has not read the message
     * @nullable
     */
  read_at: string | null;
  recipient_id: string;
  sender_id: string;
}
