/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateEssayBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
     * Optional college this essay targets
     * @nullable
     */
  college_id?: number | null;
  /** @minLength 10 */
  link_to_content: string;
  /** Student the essay belongs to */
  student_id: string;
  /** @maxLength 100 */
  type: string;
}
