/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

/**
 * the type of user the counselor would like to create
 */
export type CreateUserInputBodyRole = typeof CreateUserInputBodyRole[keyof typeof CreateUserInputBodyRole];


export const CreateUserInputBodyRole = {
  student: 'student',
  counselor: 'counselor',
} as const;
