/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTodoItemRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  completed_at?: string;
  deadline?: string;
  student_id?: string;
  todo_description: string;
  user_id?: string;
}
