/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUserInputBodyRole } from './createUserInputBodyRole';

export interface CreateUserInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** email of user for supabase signup */
  email: string;
  /**
     * Name of the user
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  /**
     * pfp key of user
     * @nullable
     */
  pfp_key: string | null;
  /** the type of user the counselor would like to create */
  role: CreateUserInputBodyRole;
}
