/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateEssayGroupBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
     * Optional description of the group
     * @nullable
     */
  description?: string | null;
  /**
     * Unique name for the group
     * @minLength 1
     * @maxLength 100
     */
  name: string;
  /** Student the group belongs to */
  student_id: string;
}
