/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface CreateUserBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  temp_password: string;
  user: User;
}
