/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateChatMessageRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
     * Message text
     * @minLength 1
     */
  message: string;
  /** User ID of the message recipient */
  recipient_id: string;
}
