/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateGlobalCollegeRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Early admission deadline */
  ea_deadline?: string;
  /** Early decision deadline */
  ed_deadline?: string;
  /** Regular decision deadline */
  rd_deadline?: string;
  /** Location of the college */
  school_location: string;
  /** Name of the college */
  school_name: string;
}
