/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTodoItemRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  completed_at?: string;
  deadline?: string;
  /** Essay this task is for; at most one of essay_id, media_id, global_college_id */
  essay_id?: string;
  /** College this task is for; at most one of essay_id, media_id, global_college_id */
  global_college_id?: number;
  /** Media this task is for; at most one of essay_id, media_id, global_college_id */
  media_id?: string;
  student_id?: string;
  todo_description: string;
  user_id?: string;
}
