/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

/**
 * Which deadline the student is applying by
 */
export type CreatePersonalCollegeApplicationRequestBodyApplicationType = typeof CreatePersonalCollegeApplicationRequestBodyApplicationType[keyof typeof CreatePersonalCollegeApplicationRequestBodyApplicationType];


export const CreatePersonalCollegeApplicationRequestBodyApplicationType = {
  EA: 'EA',
  ED: 'ED',
  RD: 'RD',
} as const;
