/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type { CreatePersonalCollegeApplicationRequestBodyApplicationType } from './createPersonalCollegeApplicationRequestBodyApplicationType';
import type { CreatePersonalCollegeApplicationRequestBodyCategory } from './createPersonalCollegeApplicationRequestBodyCategory';

export interface CreatePersonalCollegeApplicationRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Which deadline the student is applying by */
  application_type: CreatePersonalCollegeApplicationRequestBodyApplicationType;
  /** How the student categorizes this school */
  category: CreatePersonalCollegeApplicationRequestBodyCategory;
  /** ID of the global college being applied to */
  global_college_id: number;
}
