/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateMediaRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  description: string;
  length_in_mins: number;
  s3_key: string;
  /** @nullable */
  school_year: number | null;
  title: string;
}
