/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

/**
 * How the student categorizes this school
 */
export type CreatePersonalCollegeApplicationRequestBodyCategory = typeof CreatePersonalCollegeApplicationRequestBodyCategory[keyof typeof CreatePersonalCollegeApplicationRequestBodyCategory];


export const CreatePersonalCollegeApplicationRequestBodyCategory = {
  safety: 'safety',
  target: 'target',
  reach: 'reach',
} as const;
