/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface Essays {
  college_id: string;
  essay_group_id: string;
  id: string;
  link_to_content: string;
  status: string;
  student_id: string;
  type: string;
}
