/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface EssayGroups {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @nullable */
  description?: string | null;
  id: string;
  name: string;
  student_id: string;
}
