/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface EssayReviewTransaction {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** User who caused the movement. Null until auth provides the caller. */
  actor_id?: string;
  /** When a counselor marked the review complete */
  completed_at?: string;
  /** Timestamp when the transaction was created */
  created_at: string;
  /** Kind of movement: spend, refund, or adjustment */
  entry_type: string;
  /** Essay under review. Null for an adjustment. */
  essay_id?: string;
  /** Unique identifier for the transaction */
  id: string;
  /** The negative row that reversed this charge, if it was refunded */
  refund?: string;
  /** Lifecycle of a spend: open, completed, or refunded. Null for refund and adjustment rows. */
  status?: string;
  /** Student whose balance moved */
  student_id: string;
  /** Signed change to the student's balance. Negative for a spend, positive for a refund or grant. Sums to the balance. */
  subtotal: number;
  /** Timestamp when the transaction was last updated */
  updated_at: string;
}
