/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type { Essays } from './essays';

export interface EssayListBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @nullable */
  essays: Essays[] | null;
}
