/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface EssayReviewStatus {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** When a counselor completed it */
  completed_at?: string;
  /** Essay the review is for */
  essay_id: string;
  /** When the review was requested */
  requested_at: string;
  /** open, completed, or refunded */
  status: string;
  /** Student who requested the review */
  student_id: string;
  /** Ledger row this status came from */
  transaction_id: string;
}
