/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface Extracurricular {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  description: string;
  end_date?: string;
  id: number;
  leadership_role?: string;
  modified_at: string;
  name: string;
  organization: string;
  start_date: string;
  status: string;
  student_id: string;
  type: string;
  user_id: string;
}
