/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export type GetTodoItemsLinkedTo = typeof GetTodoItemsLinkedTo[keyof typeof GetTodoItemsLinkedTo];


export const GetTodoItemsLinkedTo = {
  essay: 'essay',
  media: 'media',
  college: 'college',
} as const;
