/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type { GetTodoItemsLinkedTo } from './getTodoItemsLinkedTo';
import type { GetTodoItemsSortBy } from './getTodoItemsSortBy';
import type { GetTodoItemsSortOrder } from './getTodoItemsSortOrder';
import type { GetTodoItemsStatus } from './getTodoItemsStatus';

export type GetTodoItemsParams = {
/**
 * Student whose to-do items to return; defaults to the authenticated student
 */
student_id?: string;
/**
 * Filter by completion status
 */
status?: GetTodoItemsStatus;
/**
 * Only return items linked to this essay
 */
essay_id?: string;
/**
 * Only return items linked to this media
 */
media_id?: string;
/**
 * Only return items linked to this college
 */
global_college_id?: number;
/**
 * Only return items linked to any item of this type
 */
linked_to?: GetTodoItemsLinkedTo;
/**
 * Field to sort by
 */
sort_by?: GetTodoItemsSortBy;
/**
 * Sort direction
 */
sort_order?: GetTodoItemsSortOrder;
/**
 * next_cursor from the previous page; omit to get the first page
 */
cursor?: string;
/**
 * Maximum number of to-do items to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
