/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export type GetVideoParams = {
/**
 * The S3 key/path of the video to fetch
 */
s3_key?: string;
};
