/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface GlobalCollege {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Timestamp when the college was created */
  created_at: string;
  /** Early admission deadline */
  ea_deadline?: string;
  /** Early decision deadline */
  ed_deadline?: string;
  /** Unique identifier for the college */
  id: number;
  /** Regular decision deadline */
  rd_deadline?: string;
  /** Location of the college */
  school_location: string;
  /** Name of the college */
  school_name: string;
  /** Timestamp when the college was last updated */
  updated_at: string;
}
