/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface GreetingRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
     * Name to greet
     * @maxLength 30
     */
  name: string;
}
