/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateGreetingOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Greeting message */
  message: string;
}
