/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface HealthOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Liveness status of the API */
  status: string;
}
