/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export * from './createGlobalCollegeRequestBody';
export * from './createPersonalCollegeApplicationRequestBody';
export * from './createPersonalCollegeApplicationRequestBodyApplicationType';
export * from './createPersonalCollegeApplicationRequestBodyCategory';
export * from './createTodoItemRequestBody';
export * from './errorDetail';
export * from './errorModel';
export * from './essayReviewStatus';
export * from './essayReviewTransaction';
export * from './globalCollege';
export * from './greetingMessageBody';
export * from './greetingOutputBody';
export * from './greetingRequestBody';
export * from './personalCollegeApplication';
export * from './refundEssayReviewResponseBody';
export * from './requestEssayReviewRequestBody';
export * from './setStudentReviewBalanceRequestBody';
export * from './student';
export * from './todoItem';
export * from './updateTodoItemCompletedAtInputBody';
