/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export type ListMediaParams = {
/**
 * Maximum number of media to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Number of media to skip before returning results
 * @minimum 0
 */
offset?: number;
};
