/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export type ListChatMessagesParams = {
/**
 * next_cursor from the previous page; omit to get the newest messages
 */
cursor?: string;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
