/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from './userResponse';

export interface LoginResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  access_token: string;
  error: unknown;
  expires_in: number;
  refresh_token: string;
  /** @nullable */
  reset_time: string | null;
  token_type: string;
  user: UserResponse;
}
