/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface MediaAccess {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  id: string;
  media_id: string;
  student_id: string;
}
