/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface PersonalCollegeApplication {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Which deadline the student is applying by: EA, ED, or RD */
  application_type: string;
  /** How the student categorizes this school: safety, target, or reach */
  category: string;
  created_at: string;
  /** ID of the global college being applied to */
  global_college_id: number;
  /** Unique identifier for the application */
  id: number;
  /** ID of the student who owns this application */
  student_id: string;
  updated_at: string;
}
