/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface PresignUploadResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** The S3 key/path to store elsewhere, e.g. in a media table */
  s3_key: string;
  /** A presigned URL the client PUTs the raw video bytes to */
  upload_url: string;
}
