/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type { EssayReviewTransaction } from './essayReviewTransaction';

export interface RefundEssayReviewResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** The negative row that reversed the charge */
  refund: EssayReviewTransaction;
  /** The original charge, now marked refunded */
  transaction: EssayReviewTransaction;
}
