/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface RequestEssayReviewRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
     * Number of review credits to spend. Positive; recorded on the ledger as a negative subtotal.
     * @minimum 1
     */
  amount: number;
  /** Essay to review */
  essay_id: string;
  /** Student requesting the review */
  student_id: string;
}
