/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export type SearchTodoItemsSortOrder = typeof SearchTodoItemsSortOrder[keyof typeof SearchTodoItemsSortOrder];


export const SearchTodoItemsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
