/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export type SearchTodoItemsLinkedTo = typeof SearchTodoItemsLinkedTo[keyof typeof SearchTodoItemsLinkedTo];


export const SearchTodoItemsLinkedTo = {
  essay: 'essay',
  media: 'media',
  college: 'college',
} as const;
