/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export type SearchTodoItemsSortBy = typeof SearchTodoItemsSortBy[keyof typeof SearchTodoItemsSortBy];


export const SearchTodoItemsSortBy = {
  created_at: 'created_at',
  deadline: 'deadline',
  completed_at: 'completed_at',
  updated_at: 'updated_at',
} as const;
