/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type { SearchTodoItemsLinkedTo } from './searchTodoItemsLinkedTo';
import type { SearchTodoItemsSortBy } from './searchTodoItemsSortBy';
import type { SearchTodoItemsSortOrder } from './searchTodoItemsSortOrder';
import type { SearchTodoItemsStatus } from './searchTodoItemsStatus';

export type SearchTodoItemsParams = {
/**
 * Student whose to-do items to return; defaults to the authenticated student
 */
student_id?: string;
/**
 * Filter by completion status
 */
status?: SearchTodoItemsStatus;
/**
 * Only return items linked to this essay
 */
essay_id?: string;
/**
 * Only return items linked to this media
 */
media_id?: string;
/**
 * Only return items linked to this college
 */
global_college_id?: number;
/**
 * Only return items linked to any item of this type
 */
linked_to?: SearchTodoItemsLinkedTo;
/**
 * Field to sort by
 */
sort_by?: SearchTodoItemsSortBy;
/**
 * Sort direction
 */
sort_order?: SearchTodoItemsSortOrder;
/**
 * Text to search for in to-do descriptions
 * @minLength 1
 * @maxLength 200
 */
q: string;
/**
 * next_cursor from the previous page; omit to get the first page
 */
cursor?: string;
/**
 * Maximum number of to-do items to return
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
