/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export type SearchTodoItemsStatus = typeof SearchTodoItemsStatus[keyof typeof SearchTodoItemsStatus];


export const SearchTodoItemsStatus = {
  all: 'all',
  completed: 'completed',
  incomplete: 'incomplete',
} as const;
