/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface Student {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  counselor_id: string;
  gpa: number;
  id: string;
  /** @nullable */
  organization: string | null;
  review_balance: number;
  user_id: string;
  year: string;
}
