/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface TodoItem {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @nullable */
  completed_at: string | null;
  created_at: string;
  /** @nullable */
  deadline: string | null;
  /** @nullable */
  essay_id: string | null;
  /** @nullable */
  global_college_id: number | null;
  id: string;
  /** @nullable */
  media_id: string | null;
  student_id: string;
  todo_description: string;
  updated_at: string;
  user_id: string;
}
