/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePersonalCollegeApplicationRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Which deadline the student is applying by: EA, ED, or RD */
  application_type: string;
  /** How the student categorizes this school: safety, target, or reach */
  category: string;
  /** ID of the global college being applied to */
  global_college_id: number;
}
