/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateEssayGroupBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Group to move the essay into, or null to remove it from its group */
  essay_group_id?: string;
}
