/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export type UpdateExtracurricularRequestStatus = typeof UpdateExtracurricularRequestStatus[keyof typeof UpdateExtracurricularRequestStatus];


export const UpdateExtracurricularRequestStatus = {
  doing: 'doing',
  have_done: 'have_done',
} as const;
