/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

/**
 * New status for the essay
 */
export type UpdateStatusBodyStatus = typeof UpdateStatusBodyStatus[keyof typeof UpdateStatusBodyStatus];


export const UpdateStatusBodyStatus = {
  Submitted: 'Submitted',
  Draft: 'Draft',
  Review: 'Review',
  Archived: 'Archived',
} as const;
