/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateStatusBodyStatus } from './updateStatusBodyStatus';

export interface UpdateStatusBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** New status for the essay */
  status: UpdateStatusBodyStatus;
}
