/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePersonalCollegeApplicationRankRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
     * The new 1-based rank, or null to un-rank this application
     * @nullable
     */
  rank: number | null;
}
