/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export type UpdateExtracurricularRequestType = typeof UpdateExtracurricularRequestType[keyof typeof UpdateExtracurricularRequestType];


export const UpdateExtracurricularRequestType = {
  maintenance: 'maintenance',
  investment: 'investment',
} as const;
