/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateNotificationPreferencesRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Number of days before the due date to send notifications */
  days_before_due: number;
  /** Whether the user wants to receive due date notifications */
  due_date_notifications_enabled: boolean;
  /** Whether the user wants to receive email notifications */
  email_enabled: boolean;
  /** Whether the user wants to receive notifications for past due dates */
  notify_past_due: boolean;
  /** Whether the user wants to receive weekly summary notifications */
  weekly_summary_enabled: boolean;
}
