/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */

export interface Video {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** A presigned, time-limited URL for playback. Re-fetch this endpoint if the URL expires. */
  download_url: string;
  /** The video's S3 object key/path, e.g. video-bucket/common-app-tips.mp4 */
  s3_key: string;
}
