
create table public.personal_college_applications (
    id bigint generated by default as identity primary key,
    student_id uuid not null,
    global_college_id bigint not null references public.global_colleges(id),
    application_type text not null check (application_type in ('EA', 'ED', 'RD')),
    category text not null check (category in ('safety', 'target', 'reach')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);