create table public.global_colleges (
    id bigint generated by default as identity primary key,
    school_name text not null,
    school_location text not null,
    ea_deadline timestamptz,
    ed_deadline timestamptz,
    rd_deadline timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- case insensitive unique index for school_name and school_location
create unique index idx_global_colleges_name_location_ci
on public.global_colleges (lower(school_name), lower(school_location));