create table public.greetings (
    id bigint generated by default as identity primary key,
    name varchar(30) not null,
    greeting_string text not null,
    created_at timestamptz not null default now()
);
