-- Create the extracurriculars table for student activities.
-- This stores each activity, who owns it, when it happened, and the user that created it.
create table public.extracurriculars (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    student_id uuid not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    status text not null check (status in ('doing', 'have_done')),
    type text not null check (type in ('maintenance', 'investment')),
    description text not null,
    leadership_role text,
    start_date date not null,
    end_date date,
    organization text not null
);

-- Index student and creator lookups for the new activity records.
create index idx_extracurriculars_student_id
    on public.extracurriculars (student_id);

create index idx_extracurriculars_user_id
    on public.extracurriculars (user_id);

-- Keep updated_at in sync automatically whenever a row is edited.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger extracurriculars_set_updated_at
before update on public.extracurriculars
for each row
execute function public.set_updated_at();
