/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ErrorModel,
  GetMediaAccessParams,
  GrantMediaAccessRequestBody,
  Media,
  MediaAccess
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type getMediaAccessResponse200 = {
  data: Media[] | null
  status: 200
}

export type getMediaAccessResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getMediaAccessResponseSuccess = (getMediaAccessResponse200) & {
  headers: Headers;
};
export type getMediaAccessResponseError = (getMediaAccessResponseDefault) & {
  headers: Headers;
};

export type getMediaAccessResponse = (getMediaAccessResponseSuccess | getMediaAccessResponseError)

export const getGetMediaAccessUrl = (params?: GetMediaAccessParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://127.0.0.1:8080/media-access?${stringifiedParams}` : `http://127.0.0.1:8080/media-access`
}

/**
 * Allow students to fetch only videos they have access to
 */
export const getMediaAccess = async (params?: GetMediaAccessParams, options?: RequestInit): Promise<getMediaAccessResponse> => {

  const res = await fetch(getGetMediaAccessUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMediaAccessResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMediaAccessResponse
}




export const getGetMediaAccessKey = (params?: GetMediaAccessParams,) => [`http://127.0.0.1:8080/media-access`, ...(params ? [params]: [])] as const;

export type GetMediaAccessQueryResult = NonNullable<Awaited<ReturnType<typeof getMediaAccess>>>

export const useGetMediaAccess = <TError = Promise<ErrorModel>>(
  params?: GetMediaAccessParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMediaAccess>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMediaAccessKey(params) : null);
  const swrFn = () => getMediaAccess(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type createMediaAccessResponse200 = {
  data: MediaAccess
  status: 200
}

export type createMediaAccessResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createMediaAccessResponseSuccess = (createMediaAccessResponse200) & {
  headers: Headers;
};
export type createMediaAccessResponseError = (createMediaAccessResponseDefault) & {
  headers: Headers;
};

export type createMediaAccessResponse = (createMediaAccessResponseSuccess | createMediaAccessResponseError)

export const getCreateMediaAccessUrl = () => {




  return `http://127.0.0.1:8080/media-access`
}

/**
 * Allow a counselor to give a student access to a video
 */
export const createMediaAccess = async (grantMediaAccessRequestBody: NonReadonly<GrantMediaAccessRequestBody>, options?: RequestInit): Promise<createMediaAccessResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateMediaAccessUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(grantMediaAccessRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createMediaAccessResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createMediaAccessResponse
}




export const getCreateMediaAccessMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<GrantMediaAccessRequestBody> }) => {
    return createMediaAccess(arg, options);
  }
}
export const getCreateMediaAccessMutationKey = () => [`http://127.0.0.1:8080/media-access`] as const;

export type CreateMediaAccessMutationResult = NonNullable<Awaited<ReturnType<typeof createMediaAccess>>>

export const useCreateMediaAccess = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createMediaAccess>>, TError, Key, NonReadonly<GrantMediaAccessRequestBody>, Awaited<ReturnType<typeof createMediaAccess>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateMediaAccessMutationKey();
  const swrFn = getCreateMediaAccessMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type deleteMediaAccessResponse204 = {
  data: void
  status: 204
}

export type deleteMediaAccessResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type deleteMediaAccessResponseSuccess = (deleteMediaAccessResponse204) & {
  headers: Headers;
};
export type deleteMediaAccessResponseError = (deleteMediaAccessResponseDefault) & {
  headers: Headers;
};

export type deleteMediaAccessResponse = (deleteMediaAccessResponseSuccess | deleteMediaAccessResponseError)

export const getDeleteMediaAccessUrl = (id: string,) => {




  return `http://127.0.0.1:8080/media-access/${id}`
}

/**
 * Allow a counselor to revoke a student access to a video
 */
export const deleteMediaAccess = async (id: string, options?: RequestInit): Promise<deleteMediaAccessResponse> => {

  const res = await fetch(getDeleteMediaAccessUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteMediaAccessResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteMediaAccessResponse
}




export const getDeleteMediaAccessMutationFetcher = (id: string, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteMediaAccess(id, options);
  }
}
export const getDeleteMediaAccessMutationKey = (id: string,) => [`http://127.0.0.1:8080/media-access/${id}`] as const;

export type DeleteMediaAccessMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMediaAccess>>>

export const useDeleteMediaAccess = <TError = Promise<ErrorModel>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteMediaAccess>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteMediaAccess>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteMediaAccessMutationKey(id);
  const swrFn = getDeleteMediaAccessMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
