/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Media,
  MediaAccess
} from '../../models';

import {
  getCreateMediaAccessResponseMock,
  getGetMediaAccessResponseMock
} from './media-access.faker';

export { getGetMediaAccessResponseMock, getCreateMediaAccessResponseMock } from './media-access.faker';


export const getGetMediaAccessMockHandler = (overrideResponse?: Media[] | null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Media[] | null> | Media[] | null), options?: RequestHandlerOptions) => {
  return http.get('*/media-access', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMediaAccessResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateMediaAccessMockHandler = (overrideResponse?: MediaAccess | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MediaAccess> | MediaAccess), options?: RequestHandlerOptions) => {
  return http.post('*/media-access', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateMediaAccessResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteMediaAccessMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/media-access/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getMediaAccessMock = () => [
  getGetMediaAccessMockHandler(),
  getCreateMediaAccessMockHandler(),
  getDeleteMediaAccessMockHandler()
]
