/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GreetingMessageBody
} from '../../models';

import {
  getCreateGreetingResponseMock
} from './greetings.faker';

export { getCreateGreetingResponseMock } from './greetings.faker';


export const getCreateGreetingMockHandler = (overrideResponse?: GreetingMessageBody | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GreetingMessageBody> | GreetingMessageBody), options?: RequestHandlerOptions) => {
  return http.post('*/greeting', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateGreetingResponseMock(),
      { status: 200
      })
  }, options)
}
export const getGreetingsMock = () => [
  getCreateGreetingMockHandler()
]
