/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ErrorModel,
  CreateGreetingOutputBody
} from '../../models';


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type getGreetingResponse200 = {
  data: CreateGreetingOutputBody
  status: 200
}

export type getGreetingResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getGreetingResponseSuccess = (getGreetingResponse200) & {
  headers: Headers;
};
export type getGreetingResponseError = (getGreetingResponseDefault) & {
  headers: Headers;
};

export type getGreetingResponse = (getGreetingResponseSuccess | getGreetingResponseError)

export const getGetGreetingUrl = (name: string,) => {




  return `http://127.0.0.1:3001/greeting/${name}`
}

/**
 * Get a greeting for a person by name.
 */
export const getGreeting = async (name: string, options?: RequestInit): Promise<getGreetingResponse> => {

  const res = await fetch(getGetGreetingUrl(name),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getGreetingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getGreetingResponse
}




export const getGetGreetingKey = (name: string,) => [`http://127.0.0.1:3001/greeting/${name}`] as const;

export type GetGreetingQueryResult = NonNullable<Awaited<ReturnType<typeof getGreeting>>>

export const useGetGreeting = <TError = Promise<ErrorModel>>(
  name: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getGreeting>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && name !== null && name !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetGreetingKey(name) : null);
  const swrFn = () => getGreeting(name, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
