/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateGreetingOutputBody
} from '../../models';

import {
  getGetGreetingResponseMock
} from './greetings.faker';

export { getGetGreetingResponseMock } from './greetings.faker';


export const getGetGreetingMockHandler = (overrideResponse?: CreateGreetingOutputBody | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CreateGreetingOutputBody> | CreateGreetingOutputBody), options?: RequestHandlerOptions) => {
  return http.get('*/greeting/:name', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetGreetingResponseMock(),
      { status: 200
      })
  }, options)
}
export const getGreetingsMock = () => [
  getGetGreetingMockHandler()
]
