/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  CreateGreetingOutputBody
} from '../../models';


export const getGetGreetingResponseMock = (overrideResponse: Partial<Extract<CreateGreetingOutputBody, object>> = {}): CreateGreetingOutputBody => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

