// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/GenerateNU/inspirate-consulting/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// GreetingStore is an autogenerated mock type for the GreetingStore type
type GreetingStore struct {
	mock.Mock
}

// CreateGreeting provides a mock function with given fields: ctx, greeting
func (_m *GreetingStore) CreateGreeting(ctx context.Context, greeting models.CreateGreetingInput) (*models.CreateGreetingOutput, error) {
	ret := _m.Called(ctx, greeting)

	if len(ret) == 0 {
		panic("no return value specified for CreateGreeting")
	}

	var r0 *models.CreateGreetingOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateGreetingInput) (*models.CreateGreetingOutput, error)); ok {
		return rf(ctx, greeting)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateGreetingInput) *models.CreateGreetingOutput); ok {
		r0 = rf(ctx, greeting)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CreateGreetingOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateGreetingInput) error); ok {
		r1 = rf(ctx, greeting)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGreetingStore creates a new instance of GreetingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGreetingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *GreetingStore {
	mock := &GreetingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
