/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type {
  Arguments,
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ErrorModel,
  ResetPasswordInputBody
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type resetUserPasswordResponse204 = {
  data: void
  status: 204
}

export type resetUserPasswordResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type resetUserPasswordResponseSuccess = (resetUserPasswordResponse204) & {
  headers: Headers;
};
export type resetUserPasswordResponseError = (resetUserPasswordResponseDefault) & {
  headers: Headers;
};

export type resetUserPasswordResponse = (resetUserPasswordResponseSuccess | resetUserPasswordResponseError)

export const getResetUserPasswordUrl = () => {




  return `http://127.0.0.1:8080/user/reset-password`
}

/**
 * reset user password
 */
export const resetUserPassword = async (resetPasswordInputBody: NonReadonly<ResetPasswordInputBody>, options?: RequestInit): Promise<resetUserPasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getResetUserPasswordUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(resetPasswordInputBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: resetUserPasswordResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as resetUserPasswordResponse
}




export const getResetUserPasswordMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<ResetPasswordInputBody> }) => {
    return resetUserPassword(arg, options);
  }
}
export const getResetUserPasswordMutationKey = () => [`http://127.0.0.1:8080/user/reset-password`] as const;

export type ResetUserPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetUserPassword>>>

export const useResetUserPassword = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof resetUserPassword>>, TError, Key, NonReadonly<ResetPasswordInputBody>, Awaited<ReturnType<typeof resetUserPassword>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getResetUserPasswordMutationKey();
  const swrFn = getResetUserPasswordMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type forcePasswordResetResponse204 = {
  data: void
  status: 204
}

export type forcePasswordResetResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type forcePasswordResetResponseSuccess = (forcePasswordResetResponse204) & {
  headers: Headers;
};
export type forcePasswordResetResponseError = (forcePasswordResetResponseDefault) & {
  headers: Headers;
};

export type forcePasswordResetResponse = (forcePasswordResetResponseSuccess | forcePasswordResetResponseError)

export const getForcePasswordResetUrl = (supabaseId: string,) => {




  return `http://127.0.0.1:8080/user/${supabaseId}/force-password-reset`
}

/**
 * Force a user to reset their password on next login
 */
export const forcePasswordReset = async (supabaseId: string, options?: RequestInit): Promise<forcePasswordResetResponse> => {

  const res = await fetch(getForcePasswordResetUrl(supabaseId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: forcePasswordResetResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as forcePasswordResetResponse
}




export const getForcePasswordResetMutationFetcher = (supabaseId: string, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return forcePasswordReset(supabaseId, options);
  }
}
export const getForcePasswordResetMutationKey = (supabaseId: string,) => [`http://127.0.0.1:8080/user/${supabaseId}/force-password-reset`] as const;

export type ForcePasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof forcePasswordReset>>>

export const useForcePasswordReset = <TError = Promise<ErrorModel>>(
  supabaseId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof forcePasswordReset>>, TError, Key, Arguments, Awaited<ReturnType<typeof forcePasswordReset>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getForcePasswordResetMutationKey(supabaseId);
  const swrFn = getForcePasswordResetMutationFetcher(supabaseId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
