/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreateEssayGroupBody,
  ErrorModel,
  EssayGroupListBody,
  EssayGroups
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type createEssayGroupResponse200 = {
  data: EssayGroups
  status: 200
}

export type createEssayGroupResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createEssayGroupResponseSuccess = (createEssayGroupResponse200) & {
  headers: Headers;
};
export type createEssayGroupResponseError = (createEssayGroupResponseDefault) & {
  headers: Headers;
};

export type createEssayGroupResponse = (createEssayGroupResponseSuccess | createEssayGroupResponseError)

export const getCreateEssayGroupUrl = () => {




  return `http://127.0.0.1:8080/essay-groups`
}

/**
 * Creates an essay group for a student
 */
export const createEssayGroup = async (createEssayGroupBody: NonReadonly<CreateEssayGroupBody>, options?: RequestInit): Promise<createEssayGroupResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateEssayGroupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createEssayGroupBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createEssayGroupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createEssayGroupResponse
}




export const getCreateEssayGroupMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<CreateEssayGroupBody> }) => {
    return createEssayGroup(arg, options);
  }
}
export const getCreateEssayGroupMutationKey = () => [`http://127.0.0.1:8080/essay-groups`] as const;

export type CreateEssayGroupMutationResult = NonNullable<Awaited<ReturnType<typeof createEssayGroup>>>

export const useCreateEssayGroup = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createEssayGroup>>, TError, Key, NonReadonly<CreateEssayGroupBody>, Awaited<ReturnType<typeof createEssayGroup>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateEssayGroupMutationKey();
  const swrFn = getCreateEssayGroupMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getEssayGroupsFromStudentResponse200 = {
  data: EssayGroupListBody
  status: 200
}

export type getEssayGroupsFromStudentResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getEssayGroupsFromStudentResponseSuccess = (getEssayGroupsFromStudentResponse200) & {
  headers: Headers;
};
export type getEssayGroupsFromStudentResponseError = (getEssayGroupsFromStudentResponseDefault) & {
  headers: Headers;
};

export type getEssayGroupsFromStudentResponse = (getEssayGroupsFromStudentResponseSuccess | getEssayGroupsFromStudentResponseError)

export const getGetEssayGroupsFromStudentUrl = (studentId: string,) => {




  return `http://127.0.0.1:8080/students/${studentId}/essay-groups`
}

/**
 * Shows all essay groups of a student
 */
export const getEssayGroupsFromStudent = async (studentId: string, options?: RequestInit): Promise<getEssayGroupsFromStudentResponse> => {

  const res = await fetch(getGetEssayGroupsFromStudentUrl(studentId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getEssayGroupsFromStudentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getEssayGroupsFromStudentResponse
}




export const getGetEssayGroupsFromStudentKey = (studentId: string,) => [`http://127.0.0.1:8080/students/${studentId}/essay-groups`] as const;

export type GetEssayGroupsFromStudentQueryResult = NonNullable<Awaited<ReturnType<typeof getEssayGroupsFromStudent>>>

export const useGetEssayGroupsFromStudent = <TError = Promise<ErrorModel>>(
  studentId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getEssayGroupsFromStudent>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && studentId !== null && studentId !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetEssayGroupsFromStudentKey(studentId) : null);
  const swrFn = () => getEssayGroupsFromStudent(studentId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
