/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  EssayGroupListBody,
  EssayGroups
} from '../../models';

import {
  getCreateEssayGroupResponseMock,
  getGetEssayGroupsFromStudentResponseMock
} from './essay-groups.faker';

export { getCreateEssayGroupResponseMock, getGetEssayGroupsFromStudentResponseMock } from './essay-groups.faker';


export const getCreateEssayGroupMockHandler = (overrideResponse?: EssayGroups | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<EssayGroups> | EssayGroups), options?: RequestHandlerOptions) => {
  return http.post('*/essay-groups', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateEssayGroupResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetEssayGroupsFromStudentMockHandler = (overrideResponse?: EssayGroupListBody | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<EssayGroupListBody> | EssayGroupListBody), options?: RequestHandlerOptions) => {
  return http.get('*/students/:studentId/essay-groups', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetEssayGroupsFromStudentResponseMock(),
      { status: 200
      })
  }, options)
}
export const getEssayGroupsMock = () => [
  getCreateEssayGroupMockHandler(),
  getGetEssayGroupsFromStudentMockHandler()
]
