/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  EssayGroupListBody,
  EssayGroups
} from '../../models';


export const getCreateEssayGroupResponseMock = (overrideResponse: Partial<Extract<EssayGroups, object>> = {}): EssayGroups => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), student_id: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getGetEssayGroupsFromStudentResponseMock = (overrideResponse: Partial<Extract<EssayGroupListBody, object>> = {}): EssayGroupListBody => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), essay_groups: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), student_id: faker.string.alpha({length: {min: 10, max: 20}})})), null]), ...overrideResponse})

