/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Student
} from '../../models';

import {
  getSetStudentReviewBalanceResponseMock
} from './students.faker';

export { getSetStudentReviewBalanceResponseMock } from './students.faker';


export const getSetStudentReviewBalanceMockHandler = (overrideResponse?: Student | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Student> | Student), options?: RequestHandlerOptions) => {
  return http.patch('*/students/:id/review-balance', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSetStudentReviewBalanceResponseMock(),
      { status: 200
      })
  }, options)
}
export const getStudentsMock = () => [
  getSetStudentReviewBalanceMockHandler()
]
