/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ErrorModel,
  SetStudentReviewBalanceRequestBody,
  Student
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type setStudentReviewBalanceResponse200 = {
  data: Student
  status: 200
}

export type setStudentReviewBalanceResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type setStudentReviewBalanceResponseSuccess = (setStudentReviewBalanceResponse200) & {
  headers: Headers;
};
export type setStudentReviewBalanceResponseError = (setStudentReviewBalanceResponseDefault) & {
  headers: Headers;
};

export type setStudentReviewBalanceResponse = (setStudentReviewBalanceResponseSuccess | setStudentReviewBalanceResponseError)

export const getSetStudentReviewBalanceUrl = (id: string,) => {




  return `http://127.0.0.1:8080/students/${id}/review-balance`
}

/**
 * Overwrite a student's review balance with an absolute value, recording the change in the review ledger.
 */
export const setStudentReviewBalance = async (id: string,
    setStudentReviewBalanceRequestBody: NonReadonly<SetStudentReviewBalanceRequestBody>, options?: RequestInit): Promise<setStudentReviewBalanceResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getSetStudentReviewBalanceUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setStudentReviewBalanceRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: setStudentReviewBalanceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as setStudentReviewBalanceResponse
}




export const getSetStudentReviewBalanceMutationFetcher = (id: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<SetStudentReviewBalanceRequestBody> }) => {
    return setStudentReviewBalance(id, arg, options);
  }
}
export const getSetStudentReviewBalanceMutationKey = (id: string,) => [`http://127.0.0.1:8080/students/${id}/review-balance`] as const;

export type SetStudentReviewBalanceMutationResult = NonNullable<Awaited<ReturnType<typeof setStudentReviewBalance>>>

export const useSetStudentReviewBalance = <TError = Promise<ErrorModel>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof setStudentReviewBalance>>, TError, Key, NonReadonly<SetStudentReviewBalanceRequestBody>, Awaited<ReturnType<typeof setStudentReviewBalance>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSetStudentReviewBalanceMutationKey(id);
  const swrFn = getSetStudentReviewBalanceMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
