/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  Student
} from '../../models';


export const getSetStudentReviewBalanceResponseMock = (overrideResponse: Partial<Extract<Student, object>> = {}): Student => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), counselor_id: faker.string.alpha({length: {min: 10, max: 20}}), gpa: faker.number.int(), id: faker.string.alpha({length: {min: 10, max: 20}}), organization: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), review_balance: faker.number.int(), user_id: faker.string.alpha({length: {min: 10, max: 20}}), year: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

