/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GlobalCollege
} from '../../models';

import {
  getCreateGlobalCollegeResponseMock,
  getGetGlobalCollegeResponseMock,
  getListGlobalCollegesResponseMock
} from './global-colleges.faker';

export { getListGlobalCollegesResponseMock, getCreateGlobalCollegeResponseMock, getGetGlobalCollegeResponseMock } from './global-colleges.faker';


export const getListGlobalCollegesMockHandler = (overrideResponse?: GlobalCollege[] | null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GlobalCollege[] | null> | GlobalCollege[] | null), options?: RequestHandlerOptions) => {
  return http.get('*/colleges', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListGlobalCollegesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateGlobalCollegeMockHandler = (overrideResponse?: GlobalCollege | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GlobalCollege> | GlobalCollege), options?: RequestHandlerOptions) => {
  return http.post('*/colleges', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateGlobalCollegeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetGlobalCollegeMockHandler = (overrideResponse?: GlobalCollege | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GlobalCollege> | GlobalCollege), options?: RequestHandlerOptions) => {
  return http.get('*/colleges/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetGlobalCollegeResponseMock(),
      { status: 200
      })
  }, options)
}
export const getGlobalCollegesMock = () => [
  getListGlobalCollegesMockHandler(),
  getCreateGlobalCollegeMockHandler(),
  getGetGlobalCollegeMockHandler()
]
