/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreateGlobalCollegeRequestBody,
  ErrorModel,
  GlobalCollege
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type listGlobalCollegesResponse200 = {
  data: GlobalCollege[] | null
  status: 200
}

export type listGlobalCollegesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listGlobalCollegesResponseSuccess = (listGlobalCollegesResponse200) & {
  headers: Headers;
};
export type listGlobalCollegesResponseError = (listGlobalCollegesResponseDefault) & {
  headers: Headers;
};

export type listGlobalCollegesResponse = (listGlobalCollegesResponseSuccess | listGlobalCollegesResponseError)

export const getListGlobalCollegesUrl = () => {




  return `http://127.0.0.1:8080/colleges`
}

/**
 * List all global colleges.
 */
export const listGlobalColleges = async ( options?: RequestInit): Promise<listGlobalCollegesResponse> => {

  const res = await fetch(getListGlobalCollegesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listGlobalCollegesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listGlobalCollegesResponse
}




export const getListGlobalCollegesKey = () => [`http://127.0.0.1:8080/colleges`] as const;

export type ListGlobalCollegesQueryResult = NonNullable<Awaited<ReturnType<typeof listGlobalColleges>>>

export const useListGlobalColleges = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listGlobalColleges>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListGlobalCollegesKey() : null);
  const swrFn = () => listGlobalColleges(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type createGlobalCollegeResponse200 = {
  data: GlobalCollege
  status: 200
}

export type createGlobalCollegeResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createGlobalCollegeResponseSuccess = (createGlobalCollegeResponse200) & {
  headers: Headers;
};
export type createGlobalCollegeResponseError = (createGlobalCollegeResponseDefault) & {
  headers: Headers;
};

export type createGlobalCollegeResponse = (createGlobalCollegeResponseSuccess | createGlobalCollegeResponseError)

export const getCreateGlobalCollegeUrl = () => {




  return `http://127.0.0.1:8080/colleges`
}

/**
 * Create a global college with a name, location, and optional EA/ED/RD deadlines.
 */
export const createGlobalCollege = async (createGlobalCollegeRequestBody: NonReadonly<CreateGlobalCollegeRequestBody>, options?: RequestInit): Promise<createGlobalCollegeResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateGlobalCollegeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createGlobalCollegeRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createGlobalCollegeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createGlobalCollegeResponse
}




export const getCreateGlobalCollegeMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<CreateGlobalCollegeRequestBody> }) => {
    return createGlobalCollege(arg, options);
  }
}
export const getCreateGlobalCollegeMutationKey = () => [`http://127.0.0.1:8080/colleges`] as const;

export type CreateGlobalCollegeMutationResult = NonNullable<Awaited<ReturnType<typeof createGlobalCollege>>>

export const useCreateGlobalCollege = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createGlobalCollege>>, TError, Key, NonReadonly<CreateGlobalCollegeRequestBody>, Awaited<ReturnType<typeof createGlobalCollege>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateGlobalCollegeMutationKey();
  const swrFn = getCreateGlobalCollegeMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getGlobalCollegeResponse200 = {
  data: GlobalCollege
  status: 200
}

export type getGlobalCollegeResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getGlobalCollegeResponseSuccess = (getGlobalCollegeResponse200) & {
  headers: Headers;
};
export type getGlobalCollegeResponseError = (getGlobalCollegeResponseDefault) & {
  headers: Headers;
};

export type getGlobalCollegeResponse = (getGlobalCollegeResponseSuccess | getGlobalCollegeResponseError)

export const getGetGlobalCollegeUrl = (id: number,) => {




  return `http://127.0.0.1:8080/colleges/${id}`
}

/**
 * Get a global college by ID.
 */
export const getGlobalCollege = async (id: number, options?: RequestInit): Promise<getGlobalCollegeResponse> => {

  const res = await fetch(getGetGlobalCollegeUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getGlobalCollegeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getGlobalCollegeResponse
}




export const getGetGlobalCollegeKey = (id: number,) => [`http://127.0.0.1:8080/colleges/${id}`] as const;

export type GetGlobalCollegeQueryResult = NonNullable<Awaited<ReturnType<typeof getGlobalCollege>>>

export const useGetGlobalCollege = <TError = Promise<ErrorModel>>(
  id: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getGlobalCollege>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetGlobalCollegeKey(id) : null);
  const swrFn = () => getGlobalCollege(id, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
