/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import type {
  Arguments,
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ErrorModel
} from '../../models';


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type logoutUserResponse204 = {
  data: void
  status: 204
}

export type logoutUserResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type logoutUserResponseSuccess = (logoutUserResponse204) & {
  headers: Headers;
};
export type logoutUserResponseError = (logoutUserResponseDefault) & {
  headers: Headers;
};

export type logoutUserResponse = (logoutUserResponseSuccess | logoutUserResponseError)

export const getLogoutUserUrl = () => {




  return `http://127.0.0.1:8080/user/logout`
}

/**
 * user logout
 */
export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {

  const res = await fetch(getLogoutUserUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: logoutUserResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as logoutUserResponse
}




export const getLogoutUserMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return logoutUser(options);
  }
}
export const getLogoutUserMutationKey = () => [`http://127.0.0.1:8080/user/logout`] as const;

export type LogoutUserMutationResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>

export const useLogoutUser = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof logoutUser>>, TError, Key, Arguments, Awaited<ReturnType<typeof logoutUser>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getLogoutUserMutationKey();
  const swrFn = getLogoutUserMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
