/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  Extracurricular
} from '../../models';


export const getListExtracurricularsResponseMock = (): Extracurricular[] | null => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', description: faker.string.alpha({length: {min: 10, max: 20}}), end_date: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), id: faker.number.int(), leadership_role: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), modified_at: faker.date.past().toISOString().slice(0, 19) + 'Z', name: faker.string.alpha({length: {min: 10, max: 20}}), organization: faker.string.alpha({length: {min: 10, max: 20}}), start_date: faker.date.past().toISOString().slice(0, 19) + 'Z', status: faker.string.alpha({length: {min: 10, max: 20}}), student_id: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}}), user_id: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getUpdateExtracurricularResponseMock = (overrideResponse: Partial<Extract<Extracurricular, object>> = {}): Extracurricular => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', description: faker.string.alpha({length: {min: 10, max: 20}}), end_date: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), id: faker.number.int(), leadership_role: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), modified_at: faker.date.past().toISOString().slice(0, 19) + 'Z', name: faker.string.alpha({length: {min: 10, max: 20}}), organization: faker.string.alpha({length: {min: 10, max: 20}}), start_date: faker.date.past().toISOString().slice(0, 19) + 'Z', status: faker.string.alpha({length: {min: 10, max: 20}}), student_id: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}}), user_id: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getCreateExtracurricularResponseMock = (overrideResponse: Partial<Extract<Extracurricular, object>> = {}): Extracurricular => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', description: faker.string.alpha({length: {min: 10, max: 20}}), end_date: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), id: faker.number.int(), leadership_role: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), modified_at: faker.date.past().toISOString().slice(0, 19) + 'Z', name: faker.string.alpha({length: {min: 10, max: 20}}), organization: faker.string.alpha({length: {min: 10, max: 20}}), start_date: faker.date.past().toISOString().slice(0, 19) + 'Z', status: faker.string.alpha({length: {min: 10, max: 20}}), student_id: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}}), user_id: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

