/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Extracurricular
} from '../../models';

import {
  getCreateExtracurricularResponseMock,
  getListExtracurricularsResponseMock,
  getUpdateExtracurricularResponseMock
} from './extracurriculars.faker';

export { getListExtracurricularsResponseMock, getUpdateExtracurricularResponseMock, getCreateExtracurricularResponseMock } from './extracurriculars.faker';


export const getListExtracurricularsMockHandler = (overrideResponse?: Extracurricular[] | null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Extracurricular[] | null> | Extracurricular[] | null), options?: RequestHandlerOptions) => {
  return http.get('*/extracurriculars', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListExtracurricularsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateExtracurricularMockHandler = (overrideResponse?: Extracurricular | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Extracurricular> | Extracurricular), options?: RequestHandlerOptions) => {
  return http.patch('*/extracurriculars/:id', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateExtracurricularResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateExtracurricularMockHandler = (overrideResponse?: Extracurricular | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Extracurricular> | Extracurricular), options?: RequestHandlerOptions) => {
  return http.post('*/extracurriculars/:studentID', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateExtracurricularResponseMock(),
      { status: 200
      })
  }, options)
}
export const getExtracurricularsMock = () => [
  getListExtracurricularsMockHandler(),
  getUpdateExtracurricularMockHandler(),
  getCreateExtracurricularMockHandler()
]
