/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreateExtracurricularRequest,
  ErrorModel,
  Extracurricular,
  UpdateExtracurricularRequest
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type listExtracurricularsResponse200 = {
  data: Extracurricular[] | null
  status: 200
}

export type listExtracurricularsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listExtracurricularsResponseSuccess = (listExtracurricularsResponse200) & {
  headers: Headers;
};
export type listExtracurricularsResponseError = (listExtracurricularsResponseDefault) & {
  headers: Headers;
};

export type listExtracurricularsResponse = (listExtracurricularsResponseSuccess | listExtracurricularsResponseError)

export const getListExtracurricularsUrl = () => {




  return `/api/extracurriculars`
}

/**
 * List extracurriculars for the authenticated student.
 */
export const listExtracurriculars = async ( options?: RequestInit): Promise<listExtracurricularsResponse> => {

  const res = await fetch(getListExtracurricularsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listExtracurricularsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listExtracurricularsResponse
}




export const getListExtracurricularsKey = () => [`/api/extracurriculars`] as const;

export type ListExtracurricularsQueryResult = NonNullable<Awaited<ReturnType<typeof listExtracurriculars>>>

export const useListExtracurriculars = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listExtracurriculars>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListExtracurricularsKey() : null);
  const swrFn = () => listExtracurriculars(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type updateExtracurricularResponse200 = {
  data: Extracurricular
  status: 200
}

export type updateExtracurricularResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateExtracurricularResponseSuccess = (updateExtracurricularResponse200) & {
  headers: Headers;
};
export type updateExtracurricularResponseError = (updateExtracurricularResponseDefault) & {
  headers: Headers;
};

export type updateExtracurricularResponse = (updateExtracurricularResponseSuccess | updateExtracurricularResponseError)

export const getUpdateExtracurricularUrl = (id: number,) => {




  return `/api/extracurriculars/${id}`
}

/**
 * Update fields on an extracurricular for the authenticated student.
 */
export const updateExtracurricular = async (id: number,
    updateExtracurricularRequest: NonReadonly<UpdateExtracurricularRequest>, options?: RequestInit): Promise<updateExtracurricularResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getUpdateExtracurricularUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateExtracurricularRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateExtracurricularResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateExtracurricularResponse
}




export const getUpdateExtracurricularMutationFetcher = (id: number, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<UpdateExtracurricularRequest> }) => {
    return updateExtracurricular(id, arg, options);
  }
}
export const getUpdateExtracurricularMutationKey = (id: number,) => [`/api/extracurriculars/${id}`] as const;

export type UpdateExtracurricularMutationResult = NonNullable<Awaited<ReturnType<typeof updateExtracurricular>>>

export const useUpdateExtracurricular = <TError = Promise<ErrorModel>>(
  id: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateExtracurricular>>, TError, Key, NonReadonly<UpdateExtracurricularRequest>, Awaited<ReturnType<typeof updateExtracurricular>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateExtracurricularMutationKey(id);
  const swrFn = getUpdateExtracurricularMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type createExtracurricularResponse200 = {
  data: Extracurricular
  status: 200
}

export type createExtracurricularResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createExtracurricularResponseSuccess = (createExtracurricularResponse200) & {
  headers: Headers;
};
export type createExtracurricularResponseError = (createExtracurricularResponseDefault) & {
  headers: Headers;
};

export type createExtracurricularResponse = (createExtracurricularResponseSuccess | createExtracurricularResponseError)

export const getCreateExtracurricularUrl = (studentID: string,) => {




  return `/api/extracurriculars/${studentID}`
}

/**
 * Create a new extracurricular for the given student.
 */
export const createExtracurricular = async (studentID: string,
    createExtracurricularRequest: NonReadonly<CreateExtracurricularRequest>, options?: RequestInit): Promise<createExtracurricularResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateExtracurricularUrl(studentID),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createExtracurricularRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createExtracurricularResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createExtracurricularResponse
}




export const getCreateExtracurricularMutationFetcher = (studentID: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<CreateExtracurricularRequest> }) => {
    return createExtracurricular(studentID, arg, options);
  }
}
export const getCreateExtracurricularMutationKey = (studentID: string,) => [`/api/extracurriculars/${studentID}`] as const;

export type CreateExtracurricularMutationResult = NonNullable<Awaited<ReturnType<typeof createExtracurricular>>>

export const useCreateExtracurricular = <TError = Promise<ErrorModel>>(
  studentID: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createExtracurricular>>, TError, Key, NonReadonly<CreateExtracurricularRequest>, Awaited<ReturnType<typeof createExtracurricular>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateExtracurricularMutationKey(studentID);
  const swrFn = getCreateExtracurricularMutationFetcher(studentID, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
