/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  NotificationPreferences
} from '../../models';


export const getGetNotificationPreferencesResponseMock = (overrideResponse: Partial<Extract<NotificationPreferences, object>> = {}): NotificationPreferences => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), days_before_due: faker.number.int(), due_date_notifications_enabled: faker.datatype.boolean(), email_enabled: faker.datatype.boolean(), notify_past_due: faker.datatype.boolean(), user_id: faker.string.alpha({length: {min: 10, max: 20}}), weekly_summary_enabled: faker.datatype.boolean(), ...overrideResponse})

export const getUpdateNotificationPreferencesResponseMock = (overrideResponse: Partial<Extract<NotificationPreferences, object>> = {}): NotificationPreferences => ({$schema: faker.helpers.arrayElement([faker.internet.url(), undefined]), days_before_due: faker.number.int(), due_date_notifications_enabled: faker.datatype.boolean(), email_enabled: faker.datatype.boolean(), notify_past_due: faker.datatype.boolean(), user_id: faker.string.alpha({length: {min: 10, max: 20}}), weekly_summary_enabled: faker.datatype.boolean(), ...overrideResponse})

