/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ErrorModel,
  NotificationPreferences,
  UpdateNotificationPreferencesRequestBody
} from '../../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;





 export type getNotificationPreferencesResponse200 = {
  data: NotificationPreferences
  status: 200
}

export type getNotificationPreferencesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getNotificationPreferencesResponseSuccess = (getNotificationPreferencesResponse200) & {
  headers: Headers;
};
export type getNotificationPreferencesResponseError = (getNotificationPreferencesResponseDefault) & {
  headers: Headers;
};

export type getNotificationPreferencesResponse = (getNotificationPreferencesResponseSuccess | getNotificationPreferencesResponseError)

export const getGetNotificationPreferencesUrl = () => {




  return `/api/notification-preferences`
}

/**
 * Get notification preferences for the authenticated user.
 */
export const getNotificationPreferences = async ( options?: RequestInit): Promise<getNotificationPreferencesResponse> => {

  const res = await fetch(getGetNotificationPreferencesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getNotificationPreferencesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getNotificationPreferencesResponse
}




export const getGetNotificationPreferencesKey = () => [`/api/notification-preferences`] as const;

export type GetNotificationPreferencesQueryResult = NonNullable<Awaited<ReturnType<typeof getNotificationPreferences>>>

export const useGetNotificationPreferences = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getNotificationPreferences>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetNotificationPreferencesKey() : null);
  const swrFn = () => getNotificationPreferences(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type updateNotificationPreferencesResponse200 = {
  data: NotificationPreferences
  status: 200
}

export type updateNotificationPreferencesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateNotificationPreferencesResponseSuccess = (updateNotificationPreferencesResponse200) & {
  headers: Headers;
};
export type updateNotificationPreferencesResponseError = (updateNotificationPreferencesResponseDefault) & {
  headers: Headers;
};

export type updateNotificationPreferencesResponse = (updateNotificationPreferencesResponseSuccess | updateNotificationPreferencesResponseError)

export const getUpdateNotificationPreferencesUrl = () => {




  return `/api/notification-preferences`
}

/**
 * Update notification preferences for the authenticated user.
 */
export const updateNotificationPreferences = async (updateNotificationPreferencesRequestBody: NonReadonly<UpdateNotificationPreferencesRequestBody>, options?: RequestInit): Promise<updateNotificationPreferencesResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getUpdateNotificationPreferencesUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateNotificationPreferencesRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateNotificationPreferencesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateNotificationPreferencesResponse
}




export const getUpdateNotificationPreferencesMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NonReadonly<UpdateNotificationPreferencesRequestBody> }) => {
    return updateNotificationPreferences(arg, options);
  }
}
export const getUpdateNotificationPreferencesMutationKey = () => [`/api/notification-preferences`] as const;

export type UpdateNotificationPreferencesMutationResult = NonNullable<Awaited<ReturnType<typeof updateNotificationPreferences>>>

export const useUpdateNotificationPreferences = <TError = Promise<ErrorModel>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateNotificationPreferences>>, TError, Key, NonReadonly<UpdateNotificationPreferencesRequestBody>, Awaited<ReturnType<typeof updateNotificationPreferences>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateNotificationPreferencesMutationKey();
  const swrFn = getUpdateNotificationPreferencesMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
