/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Inspirate Consulting API
 * API for the Inspirate Consulting application
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  NotificationPreferences
} from '../../models';

import {
  getGetNotificationPreferencesResponseMock,
  getUpdateNotificationPreferencesResponseMock
} from './user-notification-preferences.faker';

export { getGetNotificationPreferencesResponseMock, getUpdateNotificationPreferencesResponseMock } from './user-notification-preferences.faker';


export const getGetNotificationPreferencesMockHandler = (overrideResponse?: NotificationPreferences | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NotificationPreferences> | NotificationPreferences), options?: RequestHandlerOptions) => {
  return http.get('*/notification-preferences', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetNotificationPreferencesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateNotificationPreferencesMockHandler = (overrideResponse?: NotificationPreferences | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<NotificationPreferences> | NotificationPreferences), options?: RequestHandlerOptions) => {
  return http.put('*/notification-preferences', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateNotificationPreferencesResponseMock(),
      { status: 200
      })
  }, options)
}
export const getUserNotificationPreferencesMock = () => [
  getGetNotificationPreferencesMockHandler(),
  getUpdateNotificationPreferencesMockHandler()
]
